#!/usr/bin/env python3
"""
Build Refur/words.json from BÍN lookups via islenska.
Output: Refur/words.json  (bundled JSON word bank)
"""

import json, sys, os, random
from islenska import Bin
from extra_words import EXTRA
from extra_words2 import EXTRA2
from extra_words3 import EXTRA3
from extra_words4 import EXTRA4

b = Bin()

# ──────────────────────────────────────────────────────────────────────────────
# SENTENCE TEMPLATES
# ──────────────────────────────────────────────────────────────────────────────
#  Each case key → list of templates with "___" placeholder.
#  Index selected as (word_idx * 3 + slot_idx) % len(templates).

TMPL = {
    # Nouns: 4 templates per case
    "nef": [
        "Þetta er ___.",
        "___ er hér.",
        "Hér er ___.",
        "___ er á borðinu.",
        "___ stendur þarna.",
        "Sjáðu ___!",
        "___ kemur í dag.",
        "___ er í herberginu.",
    ],
    "thol": [
        "Ég sé ___.",
        "Við höfum ___.",
        "Hún á ___.",
        "Hann finnur ___.",
        "Við fáum ___.",
        "Þeir nota ___.",
        "Hún kaupir ___.",
        "Hann sér ___.",
    ],
    "thag": [
        "Við gefum ___ mat.",
        "Hér er gjöf frá ___.",
        "Þetta líkist ___.",
        "Við hjálpum ___.",
        "Hann þakkar ___.",
        "Við treysti ___.",
        "Hún ræðir við ___.",
        "Þeir kynna sig fyrir ___.",
    ],
    "eig": [
        "Þetta er heimili ___.",
        "Litur ___ er fallegur.",
        "Nafn ___ er sérstakt.",
        "Gæði ___ eru góð.",
        "Stærð ___ er ágæt.",
        "Þetta er vegna ___.",
        "Saga ___ er löng.",
        "Þetta er eigandi ___.",
    ],
    # Animals: more natural sentences
    "nef_dyr": [
        "___ er í garðinum.",
        "___ hleypur fast.",
        "Við eigum ___.",
        "___ er á akri.",
        "___ er hér.",
        "___ sér þig.",
        "___ er fallegur/falleg.",
        "Þetta er ___.",
    ],
    "thol_dyr": [
        "Ég sé ___.",
        "Við elum ___.",
        "Hún finnur ___.",
        "Hann sér ___.",
        "Við eigum ___.",
        "Þeir skoða ___.",
        "Hún kynni ___.",
        "Ég elska ___.",
    ],
    "thag_dyr": [
        "Við gefum ___ mat.",
        "Hann gefur ___ vatn.",
        "Hún líkist ___.",
        "Við hjálpum ___.",
        "Þeir gefa ___ skjól.",
        "Hann passar ___.",
        "Við tökum ___ til dýralæknis.",
        "Hún sér um ___.",
    ],
    "eig_dyr": [
        "Fótur ___ er stór.",
        "Þetta er leikur ___.",
        "Litur ___ er fallegur.",
        "Heimili ___ er á sléttunni.",
        "Nafn ___ er sérstakt.",
        "Þetta er bú ___.",
        "Gæði ___ eru góð.",
        "Saga ___ er löng.",
    ],
    # Verbs: sentences use conjugated form in blank
    "nef_so": [
        "Hann ___ oft.",
        "Hún ___ alltaf.",
        "Þetta ___ vel.",
        "Við ___ saman.",
        "Það ___ hér.",
        "Hann ___ á hverjum degi.",
        "Hún ___ mikið.",
        "Þeir ___ reglulega.",
    ],
    "thol_so": [
        "Hann ___ í gær.",
        "Hún ___ þar.",
        "Við ___ þá.",
        "Þeir ___ saman.",
        "Hann ___ seint í gær.",
        "Hún ___ þetta síðast.",
        "Við ___ það þá.",
        "Þeir ___ undir lok.",
    ],
    "thag_so": [
        "___ þetta!",
        "___ vel!",
        "___ nú!",
        "___ þig!",
        "___ á morgun!",
        "___ hér!",
        "___ fljótt!",
        "___ saman!",
    ],
    "eig_so": [
        "Gott ___ ef við gætum.",
        "Þó ___ betra.",
        "Hann vildi ___ þar.",
        "Betra ___ að bíða.",
        "Gott ___ ef hann kæmi.",
        "Ef hún ___, yrðum við hamingjusöm.",
        "Hann óskað ___ þetta.",
        "Betra ___ að reyna.",
    ],
    # Food category
    "nef_matur": [
        "___ er á borðinu.",
        "Þetta er ___.",
        "___ er góður/góð/gott.",
        "___ er fersk/ferskur.",
        "Hér er ___.",
        "___ er í eldhúsinu.",
        "___ er tilbúinn/tilbúin.",
        "___ lítur vel út.",
    ],
    "thol_matur": [
        "Ég borða ___.",
        "Hann smakkar ___.",
        "Við eldum ___.",
        "Hún bíður ___.",
        "Við kaupum ___.",
        "Hann raðar ___.",
        "Við bjóðum ___.",
        "Hún undirbýr ___.",
    ],
    "thag_matur": [
        "Við bætum ___ við.",
        "Hann bætir ___ í súpuna.",
        "Við gefum gest ___.",
        "Hún bætir smekk ___ við.",
        "Við smakkum ___.",
        "Við þökkum ___.",
        "Hún bætir ___ út í.",
        "Við þökkum ___ vel.",
    ],
    "eig_matur": [
        "Bragð ___ er gott.",
        "Ilmur ___ er dásamlegur.",
        "Litur ___ er fallegur.",
        "Gæði ___ eru góð.",
        "Verð ___ er hátt.",
        "Uppskrift ___ er einföld.",
        "Næring ___ er mikil.",
        "Saga ___ er löng.",
    ],
    # Nature
    "nef_nattura": [
        "___ er fallegt/falleg.",
        "Hér er ___.",
        "___ er stórt/stór.",
        "___ sést í fjarska.",
        "___ er í náttúrunni.",
        "Við sjáum ___.",
        "___ er þarna.",
        "Þetta er ___.",
    ],
    "thol_nattura": [
        "Við skoðum ___.",
        "Hún sér ___.",
        "Hann hugsar um ___.",
        "Við verndum ___.",
        "Þeir rannsaka ___.",
        "Hún kynnist ___.",
        "Við elskum ___.",
        "Hann ljósmyndar ___.",
    ],
    "thag_nattura": [
        "Við gönguferð ___ eru falleg.",  # awkward - let's use better ones
        "Hér er gjöf frá ___.",
        "Þetta líkist ___.",
        "Við njótum ___.",
        "Við verndum ___.",
        "Hún þakkar ___ tilvist.",
        "Við horfum á ___.",
        "Þeir kanna ___.",
    ],
    "eig_nattura": [
        "Fegurð ___ er ótrúleg.",
        "Stærð ___ er gríðarleg.",
        "Litur ___ er fallegur.",
        "Saga ___ er löng.",
        "Gæði ___ eru frábær.",
        "Náttúra ___ er vernduð.",
        "Hljóð ___ er kyrrlegt.",
        "Þekking ___ er mikil.",
    ],
    # Body parts
    "nef_likam": [
        "___ er á mér.",
        "Þetta er ___.",
        "___ er sterkur/sterk.",
        "___ er sárt/sár.",
        "___ er heilbrigð/heilbrigður.",
        "Hér er ___.",
        "___ er á honum.",
        "___ verkjar.",
    ],
    "thol_likam": [
        "Ég ber ___.",
        "Hún sér ___.",
        "Hann þreifar á ___.",
        "Við notum ___.",
        "Hún vinnur með ___.",
        "Hann skoðar ___.",
        "Læknirinn skoðar ___.",
        "Hún þrífur ___.",
    ],
    "thag_likam": [
        "Við gefum ___ hvíld.",
        "Hér er sár á ___.",
        "Hann sér um ___.",
        "Við hjálpum ___.",
        "Hún passar ___.",
        "Við verndum ___.",
        "Hann þagnar um ___.",
        "Hún hlutast til um ___.",
    ],
    "eig_likam": [
        "Stærð ___ er eðlileg.",
        "Litur ___ er heilbrigður.",
        "Hreyfing ___ er góð.",
        "Styrkur ___ er mikill.",
        "Liður ___ er sár.",
        "Heilsa ___ er góð.",
        "Virkni ___ er eðlileg.",
        "Hlutverk ___ er mikilvægt.",
    ],
    # Clothing
    "nef_kladi": [
        "___ er á mér.",
        "Þetta er ___.",
        "___ er nýr/ný.",
        "___ er fallegur/falleg.",
        "Hér er ___.",
        "___ er þveginn/þveginn.",
        "___ er gamall/gömul.",
        "___ er á henni.",
    ],
    "thol_kladi": [
        "Ég á ___.",
        "Hún kaupir ___.",
        "Hann notar ___.",
        "Við þvoum ___.",
        "Hún klæðir ___ á sig.",
        "Hann skoðar ___.",
        "Við sjáum ___.",
        "Hún tekur ___ af sér.",
    ],
    "thag_kladi": [
        "Hér er gjöf ___ frá.",
        "Hann þakkar ___.",
        "Við gefum ___.",
        "Hún þarf ___.",
        "Við skoðum ___.",
        "Hann treysti ___.",
        "Við bætum við ___.",
        "Hún gefur ___.",
    ],
    "eig_kladi": [
        "Litur ___ er fallegur.",
        "Stærð ___ er rétt.",
        "Gæði ___ eru góð.",
        "Efni ___ er mjúkt.",
        "Verð ___ er hátt.",
        "Áferð ___ er góð.",
        "Hönnun ___ er falleg.",
        "Þvottur ___ er auðveldur.",
    ],
}

def pick(templates, idx, slot):
    return templates[(idx * 3 + slot) % len(templates)]


def get_noun_forms(lemma, kyn, idx):
    """Return (nef_form, thol_form, thag_form, eig_form, sentences_dict) or None."""
    try:
        _, matches = b.lookup(lemma)
    except Exception:
        return None
    noun_matches = [m for m in matches if m.ofl == kyn]
    if not noun_matches:
        return None
    # prefer the match where the lemma itself is NFET
    nfet_match = next((m for m in noun_matches if m.mark == "NFET"), None)
    target = nfet_match or noun_matches[0]
    bin_id = target.bin_id
    try:
        all_forms = b.lookup_id(bin_id)
    except Exception:
        return None
    nf  = next((f.bmynd for f in all_forms if f.mark == "NFET"),  None)
    tf  = next((f.bmynd for f in all_forms if f.mark == "ÞFET"),  None)
    tgf = next((f.bmynd for f in all_forms if f.mark == "ÞGFET"), None)
    ef  = next((f.bmynd for f in all_forms if f.mark == "EFET"),  None)
    if not all([nf, tf, tgf, ef]):
        return None
    return nf, tf, tgf, ef


def get_verb_forms(lemma, idx):
    """Return (present, past, imperative, subj_past) or None."""
    try:
        _, matches = b.lookup(lemma)
    except Exception:
        return None
    so_matches = [m for m in matches if m.ofl == "so"]
    if not so_matches:
        return None
    # prefer generic active (alm/hluti), take first so
    target = next((m for m in so_matches if "alm" in str(m)), so_matches[0])
    bin_id = target.bin_id
    try:
        all_forms = b.lookup_id(bin_id)
    except Exception:
        return None
    def get(mark):
        return next((f.bmynd for f in all_forms if f.mark == mark), None)
    present  = get("GM-FH-NT-3P-ET")
    past     = get("GM-FH-ÞT-3P-ET")
    imp      = get("GM-BH-ET")
    subj_p   = get("GM-VH-ÞT-3P-ET")
    if not all([present, past, imp, subj_p]):
        return None
    return present, past, imp, subj_p


def build_entry(lemma, translation, kyn, category, idx):
    if kyn == "so":
        forms = get_verb_forms(lemma, idx)
        if not forms:
            return None
        present, past, imp, subj_p = forms
        ts = TMPL
        return {
            "base": f"að {lemma}",
            "translation": translation,
            "category": category,
            "gender": "-",
            "plurality": "-",
            "article": "-",
            "nefnifall":  {"word": present, "sentence": pick(ts["nef_so"], idx, 0)},
            "tholfall":   {"word": past,    "sentence": pick(ts["thol_so"], idx, 1)},
            "thagufall":  {"word": imp,     "sentence": pick(ts["thag_so"], idx, 2)},
            "eignarfall": {"word": subj_p,  "sentence": pick(ts["eig_so"], idx, 3)},
        }
    else:
        forms = get_noun_forms(lemma, kyn, idx)
        if not forms:
            return None
        nf, tf, tgf, ef = forms
        # pick template set
        cat_key = category.lower()
        if cat_key == "dýr":
            tnf, tth, ttg, tef = TMPL["nef_dyr"], TMPL["thol_dyr"], TMPL["thag_dyr"], TMPL["eig_dyr"]
        elif cat_key == "matur":
            tnf, tth, ttg, tef = TMPL["nef_matur"], TMPL["thol_matur"], TMPL["thag_matur"], TMPL["eig_matur"]
        elif cat_key == "náttúra":
            tnf, tth, ttg, tef = TMPL["nef_nattura"], TMPL["thol_nattura"], TMPL["thag_nattura"], TMPL["eig_nattura"]
        elif cat_key == "líkami":
            tnf, tth, ttg, tef = TMPL["nef_likam"], TMPL["thol_likam"], TMPL["thag_likam"], TMPL["eig_likam"]
        elif cat_key == "klæði":
            tnf, tth, ttg, tef = TMPL["nef_kladi"], TMPL["thol_kladi"], TMPL["thag_kladi"], TMPL["eig_kladi"]
        else:
            tnf, tth, ttg, tef = TMPL["nef"], TMPL["thol"], TMPL["thag"], TMPL["eig"]
        plural_s = "eintala"
        article_s = "án greinis"
        return {
            "base": lemma,
            "translation": translation,
            "category": category,
            "gender": kyn,
            "plurality": plural_s,
            "article": article_s,
            "nefnifall":  {"word": nf,  "sentence": pick(tnf, idx, 0)},
            "tholfall":   {"word": tf,  "sentence": pick(tth, idx, 1)},
            "thagufall":  {"word": tgf, "sentence": pick(ttg, idx, 2)},
            "eignarfall": {"word": ef,  "sentence": pick(tef, idx, 3)},
        }


# ──────────────────────────────────────────────────────────────────────────────
# WORD LIST  (lemma, english, gender/ofl)
#   kyn: "kk" | "kvk" | "hk" | "so"
# ──────────────────────────────────────────────────────────────────────────────
WORDS = {
    "Dýr": [
        # ── Domestic / Farm ──
        ("köttur",       "cat",               "kk"),
        ("hundur",       "dog",               "kk"),
        ("hestur",       "horse",             "kk"),
        ("kú",           "cow",               "kvk"),
        ("kind",         "sheep",             "kvk"),
        ("geit",         "goat",              "kvk"),
        ("svín",         "pig",               "hk"),
        ("hæna",         "hen / chicken",     "kvk"),
        ("önd",          "duck",              "kvk"),
        ("gæs",          "goose",             "kvk"),
        ("kalkúnn",      "turkey",            "kk"),
        ("kanína",       "rabbit",            "kvk"),
        ("dúfa",         "pigeon / dove",     "kvk"),
        ("sauður",       "ram",               "kk"),
        ("asni",         "donkey",            "kk"),
        ("mús",          "mouse",             "kvk"),
        ("rotta",        "rat",               "kvk"),
        ("ær",           "ewe",               "kvk"),
        ("naut",         "bull / ox",         "hk"),
        ("kítur",        "tomcat",            "kk"),
        ("rakki",        "dog (colloq.)",     "kk"),
        # ── Young animals ──
        ("hvelpur",      "puppy",             "kk"),
        ("kettlingur",   "kitten",            "kk"),
        ("folald",       "foal",              "hk"),
        ("lamb",         "lamb",              "hk"),
        ("kálfur",       "calf",              "kk"),
        ("gríss",        "piglet",            "kk"),
        ("kíðlingur",    "kid (young goat)",  "kk"),
        ("gæslingur",    "gosling",           "kk"),
        ("andarungi",    "duckling",          "kk"),
        # ── Small mammals ──
        ("íkorni",       "squirrel",          "kk"),
        ("hedingur",     "hedgehog",          "kk"),
        ("nagdýr",       "rodent",            "hk"),
        # ── Wild (Iceland / Arctic) ──
        ("refur",        "fox",               "kk"),
        ("úlfur",        "wolf",              "kk"),
        ("björn",        "bear",              "kk"),
        ("melrakki",     "arctic fox",        "kk"),
        ("hreindýr",     "reindeer",          "hk"),
        ("ísbjörn",      "polar bear",        "kk"),
        # ── Birds (Iceland) ──
        ("rjúpa",        "ptarmigan",         "kvk"),
        ("lundi",        "puffin",            "kk"),
        ("máfur",        "seagull",           "kk"),
        ("kría",         "Arctic tern",       "kvk"),
        ("skarfur",      "cormorant",         "kk"),
        ("hrafn",        "raven",             "kk"),
        ("þröstur",      "thrush",            "kk"),
        ("svanur",       "swan",              "kk"),
        ("fálki",        "falcon",            "kk"),
        ("örn",          "eagle",             "kk"),
        ("uggla",        "owl",               "kvk"),
        ("spör",         "sparrow",           "kk"),
        ("trani",        "crane",             "kk"),
        ("rauðbrystingur","robin",            "kk"),
        ("skógarþröstur","song thrush",       "kk"),
        # ── Sea creatures ──
        ("fiskur",       "fish",              "kk"),
        ("lax",          "salmon",            "kk"),
        ("þorskur",      "cod",               "kk"),
        ("síld",         "herring",           "kvk"),
        ("hákarl",       "shark",             "kk"),
        ("hvalur",       "whale",             "kk"),
        ("delfín",       "dolphin",           "kk"),
        ("selur",        "seal",              "kk"),
        ("rosmhvalur",   "walrus",            "kk"),
        ("rækja",        "shrimp",            "kvk"),
        ("humar",        "lobster",           "kk"),
        ("krabbi",       "crab",              "kk"),
        ("ufsi",         "saithe / pollock",  "kk"),
        ("steinbítur",   "wolffish",          "kk"),
        ("skata",        "ray",               "kvk"),
        ("lúða",         "halibut",           "kvk"),
        ("bleikja",      "Arctic char",       "kvk"),
        ("ýsa",          "haddock",           "kvk"),
        ("karfi",        "redfish",           "kk"),
        # ── Insects / small invertebrates ──
        ("fluga",        "fly",               "kvk"),
        ("býfluga",      "bee",               "kvk"),
        ("kumbaldur",    "bumblebee",         "kk"),
        ("maur",         "ant",               "kk"),
        ("fiðrildi",     "butterfly",         "hk"),
        ("könguló",      "spider",            "kvk"),
        ("maðkur",       "worm",              "kk"),
        ("snigill",      "snail",             "kk"),
        ("lirfa",        "caterpillar",       "kvk"),
        ("maríubjölla",  "ladybug",           "kvk"),
        ("þý",           "mosquito",          "kvk"),
        ("flærða",       "moth",              "kvk"),
        # ── Reptiles / Amphibians ──
        ("ormur",        "snake",             "kk"),
        ("eðla",         "lizard",            "kvk"),
        ("skjaldbaka",   "turtle",            "kvk"),
        ("krokódíll",    "crocodile",         "kk"),
        ("froskur",      "frog",              "kk"),
        ("padda",        "toad",              "kvk"),
        # ── Birds (World) ──
        ("fugl",         "bird",              "kk"),
        ("páfagaukur",   "parrot",            "kk"),
        ("flamingo",     "flamingo",          "kk"),
        ("strútur",      "ostrich",           "kk"),
        ("pengvín",      "penguin",           "kk"),
        ("pelíkani",     "pelican",           "kk"),
        # ── Wild (World) ──
        ("ljón",         "lion",              "hk"),
        ("tígur",        "tiger",             "kk"),
        ("fíll",         "elephant",          "kk"),
        ("gíraffi",      "giraffe",           "kk"),
        ("sebrahestur",  "zebra",             "kk"),
        ("api",          "monkey",            "kk"),
        ("gorilla",      "gorilla",           "kk"),
        ("kengúrú",      "kangaroo",          "kk"),
        ("flóðhestur",   "hippopotamus",      "kk"),
        ("nashyrningur", "rhinoceros",        "kk"),
        ("léopard",      "leopard",           "kk"),
        ("jakali",       "jackal",            "kk"),
        ("kojóti",       "coyote",            "kk"),
        ("kamelur",      "camel",             "kk"),
        ("panda",        "panda",             "kk"),
        ("koala",        "koala",             "kk"),
        ("mangústa",     "mongoose",          "kvk"),
        ("dreki",        "dragon",            "kk"),
        ("einhyrningur", "unicorn",           "kk"),
    ],

    "Nöfn": [
        # ── People / Family ──
        ("maður",        "man / person",      "kk"),
        ("kona",         "woman",             "kvk"),
        ("barn",         "child",             "hk"),
        ("krakki",       "kid (child)",       "kk"),
        ("drengur",      "boy",               "kk"),
        ("stúlka",       "girl",              "kvk"),
        ("piltur",       "lad / boy",         "kk"),
        ("stelpa",       "girl (colloq.)",    "kvk"),
        ("unglingur",    "teenager",          "kk"),
        ("faðir",        "father",            "kk"),
        ("móðir",        "mother",            "kvk"),
        ("foreldri",     "parent",            "hk"),
        ("sonur",        "son",               "kk"),
        ("dóttir",       "daughter",          "kvk"),
        ("bróðir",       "brother",           "kk"),
        ("systir",       "sister",            "kvk"),
        ("afi",          "grandfather",       "kk"),
        ("amma",         "grandmother",       "kvk"),
        ("langafi",      "great-grandfather", "kk"),
        ("langamma",     "great-grandmother", "kvk"),
        ("frændi",       "uncle / male cousin","kk"),
        ("frænka",       "aunt / female cousin","kvk"),
        ("eiginmaður",   "husband",           "kk"),
        ("eiginkona",    "wife",              "kvk"),
        ("maki",         "spouse",            "kk"),
        ("vinur",        "friend (male)",     "kk"),
        ("vinkona",      "friend (female)",   "kvk"),
        ("félagi",       "companion",         "kk"),
        ("nágranni",     "neighbour",         "kk"),
        ("gestur",       "guest",             "kk"),
        # ── Occupations ──
        ("kennari",      "teacher",           "kk"),
        ("læknir",       "doctor",            "kk"),
        ("tannlæknir",   "dentist",           "kk"),
        ("lyfsali",      "pharmacist",        "kk"),
        ("hjúkrunarfræðingur","nurse",        "kk"),
        ("sálfræðingur", "psychologist",      "kk"),
        ("lögmaður",     "lawyer",            "kk"),
        ("bókari",       "accountant",        "kk"),
        ("ritari",       "secretary",         "kk"),
        ("verkfræðingur","engineer",          "kk"),
        ("forritari",    "programmer",        "kk"),
        ("hönnuður",     "designer",          "kk"),
        ("arkitekt",     "architect",         "kk"),
        ("ljósmyndari",  "photographer",      "kk"),
        ("blaðamaður",   "journalist",        "kk"),
        ("bóndi",        "farmer",            "kk"),
        ("sjómaður",     "sailor",            "kk"),
        ("listamaður",   "artist",            "kk"),
        ("rithöfundur",  "author",            "kk"),
        ("leikari",      "actor",             "kk"),
        ("tónlistarmaður","musician",         "kk"),
        ("lögreglumaður","police officer",    "kk"),
        ("björgunarmaður","rescue worker",    "kk"),
        ("eldvörður",    "firefighter",       "kk"),
        ("þjónn",        "waiter / servant",  "kk"),
        ("nemandi",      "student",           "kk"),
        ("þjálfari",     "coach / trainer",   "kk"),
        ("kaupmaður",    "merchant",          "kk"),
        ("smiður",       "craftsman / smith", "kk"),
        ("rafvirki",     "electrician",       "kk"),
        ("þrif­amaður",  "cleaner",           "kk"),
        ("stjórnandi",   "manager",           "kk"),
        ("skipstjóri",   "captain (ship)",    "kk"),
        ("flugmaður",    "pilot",             "kk"),
        ("ökumaður",     "driver",            "kk"),
        ("prestur",      "priest / pastor",   "kk"),
        ("leikjahönnuður","game designer",    "kk"),
        # ── Places ──
        ("bær",          "farm / town",       "kk"),
        ("borg",         "city",              "kvk"),
        ("þorp",         "village",           "hk"),
        ("hús",          "house",             "hk"),
        ("íbúð",         "apartment",         "kvk"),
        ("skóli",        "school",            "kk"),
        ("háskóli",      "university",        "kk"),
        ("sjúkrahús",    "hospital",          "hk"),
        ("verslun",      "store",             "kvk"),
        ("búð",          "shop",              "kvk"),
        ("markaður",     "market",            "kk"),
        ("veitingastaður","restaurant",       "kk"),
        ("kaffihús",     "café",              "hk"),
        ("bókasafn",     "library",           "hk"),
        ("kirkja",       "church",            "kvk"),
        ("dómkirkja",    "cathedral",         "kvk"),
        ("hótel",        "hotel",             "hk"),
        ("flugstoð",     "airport",           "kvk"),
        ("höfn",         "harbour / port",    "kvk"),
        ("brú",          "bridge",            "kvk"),
        ("vegur",        "road",              "kk"),
        ("stígur",       "path / trail",      "kk"),
        ("gata",         "street",            "kvk"),
        ("torg",         "square / plaza",    "hk"),
        ("leiksvæði",    "playground",        "hk"),
        ("garður",       "garden / yard",     "kk"),
        ("strönd",       "beach",             "kvk"),
        ("ey",           "island",            "kvk"),
        ("land",         "country / land",    "hk"),
        ("sveit",        "countryside",       "kvk"),
        ("iðnaðarsvæði", "industrial area",   "hk"),
        ("listamiðstöð", "arts centre",       "kvk"),
        ("sundlaug",     "swimming pool",     "kvk"),
        ("íþróttamiðstöð","sports centre",    "kvk"),
        ("listasafn",    "art gallery",       "hk"),
        ("þjóðmenningarhús","cultural centre","hk"),
        ("gistiheimili", "guesthouse",        "hk"),
        ("herbergi",     "room",              "hk"),
        ("eldhús",       "kitchen",           "hk"),
        ("stofa",        "living room",       "kvk"),
        ("svefnherbergi","bedroom",           "hk"),
        ("baðherbergi",  "bathroom",          "hk"),
        ("klósett",      "toilet",            "hk"),
        ("forstofa",     "hallway / foyer",   "kvk"),
        ("ráðhús",       "town hall",         "hk"),
        ("dómhús",       "courthouse",        "hk"),
        ("fangelsi",     "prison",            "hk"),
        ("leikskóli",    "kindergarten",      "kk"),
        ("grunnskóli",   "elementary school", "kk"),
        # ── Abstract / Everyday concepts ──
        ("dagur",        "day",               "kk"),
        ("nótt",         "night",             "kvk"),
        ("morgunn",      "morning",           "kk"),
        ("kvöld",        "evening",           "hk"),
        ("hádegi",       "noon / midday",     "hk"),
        ("miðnætti",     "midnight",          "hk"),
        ("vika",         "week",              "kvk"),
        ("mánuður",      "month",             "kk"),
        ("ár",           "year",              "hk"),
        ("klukkustund",  "hour",              "kvk"),
        ("mínúta",       "minute",            "kvk"),
        ("sekúnda",      "second",            "kvk"),
        ("stund",        "moment / while",    "kvk"),
        ("tími",         "time / lesson",     "kk"),
        ("saga",         "story / history",   "kvk"),
        ("bók",          "book",              "kvk"),
        ("orð",          "word",              "hk"),
        ("nafn",         "name",              "hk"),
        ("spurning",     "question",          "kvk"),
        ("svar",         "answer",            "hk"),
        ("vandamál",     "problem",           "hk"),
        ("lausn",        "solution",          "kvk"),
        ("hugmynd",      "idea",              "kvk"),
        ("draumur",      "dream",             "kk"),
        ("von",          "hope",              "kvk"),
        ("gleði",        "joy",               "kvk"),
        ("sorg",         "grief / sorrow",    "kvk"),
        ("reiði",        "anger",             "kvk"),
        ("ást",          "love",              "kvk"),
        ("vinátта",      "friendship",        "kvk"),
        ("traust",       "trust",             "hk"),
        ("trú",          "faith / belief",    "kvk"),
        ("leynd",        "secret",            "kvk"),
        ("saga",         "history / story",   "kvk"),
        ("líf",          "life",              "hk"),
        ("dauði",        "death",             "kk"),
        ("heilsa",       "health",            "kvk"),
        ("öryggi",       "safety / security", "hk"),
        ("frelsi",       "freedom",           "hk"),
        ("réttlæti",     "justice",           "hk"),
        ("friður",       "peace",             "kk"),
        ("stríð",        "war",               "hk"),
        ("sigur",        "victory",           "kk"),
        ("tap",          "loss / defeat",     "hk"),
        ("leikur",       "game",              "kk"),
        ("glíma",        "wrestling (Icel.)", "kvk"),
        ("list",         "art",               "kvk"),
        ("tónlist",      "music",             "kvk"),
        ("dans",         "dance",             "kk"),
        ("þjóðlag",      "folk melody",       "hk"),
        ("bréf",         "letter",            "hk"),
        ("sendandi",     "sender",            "kk"),
        ("viðtakandi",   "recipient",         "kk"),
        ("hlutfall",     "ratio / percentage","hk"),
        ("fjöldi",       "number / quantity", "kk"),
        ("gildi",        "value",             "hk"),
        ("verð",         "price",             "hk"),
        ("peningur",     "money / coin",      "kk"),
        ("greiðsla",     "payment",           "kvk"),
        ("skattur",      "tax",               "kk"),
        ("þjóðarframleiðsla","GDP",           "kvk"),
        ("auður",        "wealth",            "kk"),
        ("fátækt",       "poverty",           "kvk"),
        ("menntun",      "education",         "kvk"),
        ("þekking",      "knowledge",         "kvk"),
        ("reynsla",      "experience",        "kvk"),
        ("hæfni",        "ability / skill",   "kvk"),
        ("áhugi",        "interest",          "kk"),
        ("gáfa",         "talent / gift",     "kvk"),
        ("þroski",       "maturity",          "kk"),
        ("framfarir",    "progress",          "kvk"),
        ("breyting",     "change",            "kvk"),
        ("þróun",        "development",       "kvk"),
        ("uppgötvun",    "discovery",         "kvk"),
        ("bylting",      "revolution",        "kvk"),
        ("menning",      "culture",           "kvk"),
        ("hefð",         "tradition",         "kvk"),
        ("siður",        "custom / habit",    "kk"),
        ("gildi",        "values (moral)",    "hk"),
        ("lög",          "law",               "hk"),
        ("regla",        "rule",              "kvk"),
        ("réttur",       "right / dish",      "kk"),
        ("skylda",       "duty",              "kvk"),
        ("ábyrgð",       "responsibility",    "kvk"),
        ("samstarf",     "cooperation",       "hk"),
        ("stjórnmál",    "politics",          "hk"),
        ("kjör",         "election",          "hk"),
        ("þing",         "parliament",        "hk"),
        ("ríkisstjórn",  "government",        "kvk"),
        ("flokkur",      "party / group",     "kk"),
        ("samband",      "union / connection","hk"),
        ("samfélag",     "society",           "hk"),
        ("þjóð",         "nation / people",   "kvk"),
        ("ríki",         "state / country",   "hk"),
        ("heimur",       "world",             "kk"),
        ("jörð",         "earth",             "kvk"),
        ("tungumál",     "language",          "hk"),
        ("málið",        "the language (def)","hk"),
        ("skilaboð",     "message",           "hk"),
        ("fréttir",      "news",              "kvk"),
        ("tímarit",      "magazine",          "hk"),
        ("dagblað",      "newspaper",         "hk"),
        ("kvikmynd",     "film / movie",      "kvk"),
        ("þáttur",       "episode / programme","kk"),
        ("leikrit",      "play (theatre)",    "hk"),
        ("skáld",        "poet",              "hk"),
        ("kvæði",        "poem",              "hk"),
        ("saga",         "tale",              "kvk"),
        ("smásaga",      "short story",       "kvk"),
        ("skáldsaga",    "novel",             "kvk"),
        ("handrit",      "manuscript",        "hk"),
        ("bókmennta­safn","literary archive", "hk"),
    ],

    "Hlutir": [
        # ── Furniture / Home ──
        ("stóll",        "chair",             "kk"),
        ("borð",         "table",             "hk"),
        ("rúm",          "bed",               "hk"),
        ("sófi",         "sofa / couch",      "kk"),
        ("skápur",       "cupboard / cabinet","kk"),
        ("hillur",       "shelf",             "kvk"),
        ("lampi",        "lamp",              "kk"),
        ("glugginn",     "the window",        "kk"),
        ("gluggi",       "window",            "kk"),
        ("hurð",         "door",              "kvk"),
        ("gólf",         "floor",             "hk"),
        ("loft",         "ceiling / loft",    "hk"),
        ("veggur",       "wall",              "kk"),
        ("teppið",       "the carpet",        "hk"),
        ("teppi",        "carpet / blanket",  "hk"),
        ("koddi",        "pillow",            "kk"),
        ("dýna",         "mattress / duvet",  "kvk"),
        ("þvottavél",    "washing machine",   "kvk"),
        ("uppþvottavél", "dishwasher",        "kvk"),
        ("ísskápur",     "refrigerator",      "kk"),
        ("ofn",          "oven",              "kk"),
        ("eldavél",      "stove / cooker",    "kvk"),
        ("örbylgjuofn",  "microwave",         "kk"),
        ("blendari",     "blender",           "kk"),
        ("ristill",      "toaster",           "kk"),
        ("hitari",       "heater",            "kk"),
        ("loftræstir",   "air conditioner",   "kk"),
        ("þurrkari",     "dryer",             "kk"),
        ("stofnmál",     "plumbing (system)", "hk"),
        ("þvottaþvari",  "laundry detergent", "kk"),
        # ── Kitchen items ──
        ("diskur",       "dish / plate",      "kk"),
        ("bollur",       "cup / bowl",        "kk"),
        ("glas",         "glass",             "hk"),
        ("mál",          "pan / pot",         "hk"),
        ("panna",        "frying pan",        "kvk"),
        ("skál",         "bowl",              "kvk"),
        ("hnífur",       "knife",             "kk"),
        ("gaffall",      "fork",              "kk"),
        ("skeið",        "spoon",             "kvk"),
        ("kastróll",     "saucepan",          "kk"),
        ("þvottabursti",  "washing brush",    "kk"),
        ("glertegund",   "type of glass",     "kvk"),
        ("kanna",        "jug / teapot",      "kvk"),
        ("þykni",        "lid",               "hk"),
        # ── Tools ──
        ("hamar",        "hammer",            "kk"),
        ("skrúfjárn",    "screwdriver",       "hk"),
        ("nál",          "nail / needle",     "kvk"),
        ("skrúfa",       "screw",             "kvk"),
        ("sög",          "saw",               "kvk"),
        ("borr",         "drill",             "hk"),
        ("stigi",        "ladder",            "kk"),
        ("skúffa",       "shovel / drawer",   "kvk"),
        ("tangar",       "pliers",            "kk"),
        ("lykill",       "key / wrench",      "kk"),
        ("skissublokk",  "sketchpad",         "kk"),
        ("pensill",      "paintbrush",        "kk"),
        ("krít",         "chalk",             "kvk"),
        ("tússkrifari",  "marker pen",        "kk"),
        # ── Stationery / School ──
        ("blýantur",     "pencil",            "kk"),
        ("penni",        "pen",               "kk"),
        ("bók",          "book",              "kvk"),
        ("bækur",        "books (pl.)",       "kvk"),
        ("blaðsíða",     "page",              "kvk"),
        ("pappír",       "paper",             "kk"),
        ("mappa",        "folder / binder",   "kvk"),
        ("strokleður",   "eraser",            "hk"),
        ("skúffa",       "drawer",            "kvk"),
        ("línustrikari", "ruler",             "kk"),
        ("klippa",       "scissors",          "kvk"),
        ("límbandi",     "tape",              "hk"),
        ("lím",          "glue",              "hk"),
        ("pakki",        "package",           "kk"),
        ("kassi",        "box / crate",       "kk"),
        # ── Technology ──
        ("tölva",        "computer",          "kvk"),
        ("sími",         "phone / telephone", "kk"),
        ("sjónvarp",     "television",        "hk"),
        ("útvarp",       "radio",             "hk"),
        ("myndavél",     "camera",            "kvk"),
        ("þrjótari",     "printer",           "kk"),
        ("skjár",        "screen / monitor",  "kk"),
        ("lyklaborð",    "keyboard",          "hk"),
        ("mús",          "computer mouse",    "kvk"),
        ("snertiskjár",  "touchscreen",       "kk"),
        ("höfuðtalar",   "headphones",        "kk"),
        ("myndband",     "video",             "hk"),
        ("geisladiskur", "CD / disk",         "kk"),
        ("minni",        "memory",            "hk"),
        # ── Transportation ──
        ("bíll",         "car",               "kk"),
        ("rúta",         "bus",               "kvk"),
        ("þjóðvegavagn", "tram",              "kk"),
        ("lest",         "train",             "kvk"),
        ("flugvél",      "airplane",          "kvk"),
        ("helikopter",   "helicopter",        "kk"),
        ("skip",         "ship",              "hk"),
        ("bátur",        "boat",              "kk"),
        ("reiðhjól",     "bicycle",           "hk"),
        ("hjól",         "wheel",             "hk"),
        ("mótorhjól",    "motorcycle",        "hk"),
        ("bifreið",      "motor vehicle",     "kvk"),
        ("strætisvagn",  "city bus",          "kk"),
        ("lestarstöð",   "train station",     "kvk"),
        ("flugstöð",     "airport terminal",  "kvk"),
        ("rútumiðstöð",  "bus terminal",      "kvk"),
        ("gjaldstöð",    "toll booth",        "kvk"),
        ("eldsneytisverslun","petrol station", "kvk"),
        ("bílaplan",     "car park",          "hk"),
        ("stýri",        "steering wheel",    "hk"),
        ("bremsa",       "brake",             "kvk"),
        ("fleyg",        "gear",              "kk"),
        ("öryggisbelti", "seatbelt",          "hk"),
        # ── Bag / Accessories ──
        ("taska",        "bag / briefcase",   "kvk"),
        ("bakpoki",      "backpack",          "kk"),
        ("veski",        "wallet / purse",    "hk"),
        ("úr",           "watch",             "hk"),
        ("gleraugu",     "glasses",           "hk"),
        ("solgleraugu",  "sunglasses",        "hk"),
        ("hljómtæki",    "headset",           "hk"),
        ("kertafata",    "candle holder",     "kvk"),
        ("mynd",         "picture / image",   "kvk"),
        ("ramma",        "picture frame",     "kk"),
        # ── Sports / Leisure ──
        ("knöttur",      "ball",              "kk"),
        ("net",          "net",               "hk"),
        ("golfkylfa",    "golf club",         "kvk"),
        ("skíður",       "skis",              "kk"),
        ("skriðskó",     "ice skates",        "kk"),
        ("sund",         "swimming",          "hk"),
        ("kafi",         "scuba diving",      "kk"),
        ("tjald",        "tent",              "hk"),
        ("svefnpoki",    "sleeping bag",      "kk"),
        ("fiskistöng",   "fishing rod",       "kvk"),
        ("net",          "fishing net",       "hk"),
        ("byssur",       "gun",               "kvk"),
        ("ör",           "arrow",             "kvk"),
        ("bogi",         "bow",               "kk"),
        # ── Musical Instruments ──
        ("gítar",        "guitar",            "kk"),
        ("píanó",        "piano",             "hk"),
        ("fiðla",        "violin",            "kvk"),
        ("selló",        "cello",             "hk"),
        ("klarínett",    "clarinet",          "hk"),
        ("flaut",        "flute",             "kvk"),
        ("trompet",      "trumpet",           "hk"),
        ("tromma",       "drum",              "kvk"),
        ("harpa",        "harp",              "kvk"),
        ("basskítara",   "bass guitar",       "kk"),
        ("munnharmóníka","harmonica",         "kvk"),
        ("samljómari",   "synthesizer",       "kk"),
        # ── Other everyday objects ──
        ("stigi",        "step / ladder",     "kk"),
        ("lyftari",      "elevator",          "kk"),
        ("sorp",         "rubbish / trash",   "hk"),
        ("ruslatunna",   "rubbish bin",       "kvk"),
        ("tígull",       "tile",              "kk"),
        ("botn",         "bottom",            "kk"),
        ("toppur",       "top",               "kk"),
        ("hlið",         "side / gate",       "kvk"),
        ("brún",         "edge / brow",       "kvk"),
        ("horn",         "corner / horn",     "hk"),
        ("lag",          "layer",             "hk"),
        ("hlutfall",     "ratio",             "hk"),
        ("kerfi",        "system",            "hk"),
        ("hluti",        "part",              "kk"),
        ("vandinn",      "the problem",       "kk"),
        ("verkefni",     "project / task",    "hk"),
        ("áætlun",       "plan / schedule",   "kvk"),
        ("samningur",    "contract",          "kk"),
        ("skjal",        "document",          "hk"),
        ("þjónusta",     "service",           "kvk"),
        ("vara",         "product / goods",   "kvk"),
        ("panta",        "order (noun)",      "kvk"),
        ("tilboð",       "offer",             "hk"),
        ("verð",         "price",             "hk"),
        ("verðlag",      "price level",       "hk"),
        ("kaup",         "purchase",          "hk"),
        ("sala",         "sale",              "kvk"),
        ("þátttakandi", "participant",        "kk"),
        ("veðmál",       "bet",               "hk"),
        ("gjöf",         "gift",              "kvk"),
        ("umbúðir",      "packaging",         "kvk"),
        ("póstur",       "post / mail",       "kk"),
        ("póstkassi",    "mailbox",           "kk"),
        ("klukkna",      "clock / bell",      "kvk"),
        ("tæki",         "device / tool",     "hk"),
        ("vélin",        "the machine",       "kvk"),
        ("vél",          "machine / engine",  "kvk"),
        ("kerfi",        "system",            "hk"),
        ("framkvæmd",    "implementation",    "kvk"),
        ("þvottabaðkar", "bathtub",           "kk"),
        ("sturta",       "shower",            "kvk"),
        ("samloka",      "sandwich",          "kvk"),
        ("fatnaður",     "clothing",          "kk"),
        ("umbúðir",      "wrapping",          "kvk"),
    ],

    "Nýyrði": [
        # ── Digital / Tech neologisms ──
        ("tölva",        "computer",          "kvk"),
        ("sími",         "telephone / phone", "kk"),
        ("farsími",      "mobile phone",      "kk"),
        ("spjaldtölva",  "tablet",            "kvk"),
        ("sjónvarp",     "television",        "hk"),
        ("útvarp",       "radio",             "hk"),
        ("þyrla",        "helicopter",        "kvk"),
        ("geimfar",      "spacecraft",        "hk"),
        ("tölvupóstur",  "email",             "kk"),
        ("vefsíða",      "website",           "kvk"),
        ("lyklaborð",    "keyboard",          "hk"),
        ("forrit",       "app / program",     "hk"),
        ("hugbúnaður",   "software",          "kk"),
        ("vélbúnaður",   "hardware",          "kk"),
        ("skjávarpi",    "projector",         "kk"),
        ("þráðlaust",    "wireless",          "hk"),
        ("netfang",      "email address",     "hk"),
        ("lykilorð",     "password",          "hk"),
        ("notandi",      "user",              "kk"),
        ("gagnasafn",    "database",          "hk"),
        ("skýjaþjónusta","cloud service",     "kvk"),
        ("gervigreind",  "artificial intell.","kvk"),
        ("vélnám",       "machine learning",  "hk"),
        ("reiknirit",    "algorithm",         "hk"),
        ("hugrænn",      "conceptual (adj.)", "kk"),
        ("stafrænt",     "digital (neut.)",   "hk"),
        ("þrívíðar",     "3D",                "kk"),
        ("sýndarveruleiki","virtual reality",  "kk"),
        ("blönduð veruleiki","mixed reality",  "kvk"),
        ("kraftorð",     "keyword",           "hk"),
        ("skúff",        "screenshot",        "kvk"),
        ("uppfærsla",    "update",            "kvk"),
        ("niðurhal",     "download",          "hk"),
        ("upphal",       "upload",            "hk"),
        ("smækktæki",    "scanner",           "kk"),
        ("hleðsla",      "charging",          "kvk"),
        ("rafhlöðu",     "battery",           "kvk"),
        ("hlutbundinn",  "object-oriented",   "kk"),
        # ── Science / Modern concepts ──
        ("orkugjafi",    "energy source",     "kk"),
        ("sólarorka",    "solar energy",      "kvk"),
        ("vindorka",     "wind energy",       "kvk"),
        ("rafmagn",      "electricity",       "hk"),
        ("efnasamband",  "chemical compound", "hk"),
        ("fruma",        "cell (biology)",    "kvk"),
        ("gen",          "gene",              "hk"),
        ("erfðaefni",    "genetic material",  "hk"),
        ("sæfing",       "vaccination",       "kvk"),
        ("lyf",          "medicine / drug",   "hk"),
        ("meðferð",      "treatment",         "kvk"),
        ("greining",     "diagnosis",         "kvk"),
        ("þróunarfræði", "evolutionary science","kvk"),
        ("loftslagsbreytingar","climate change","kvk"),
        ("hlýnun",       "warming",           "kvk"),
        ("gróðurhúsaáhrif","greenhouse effect","hk"),
        ("kolefni",      "carbon",            "hk"),
        ("vistvænt",     "eco-friendly",      "hk"),
        ("endurnýjanlegt","renewable (neut.)", "hk"),
        ("úrgangur",     "waste",             "kk"),
        ("endurvinnsla", "recycling",         "kvk"),
        ("þjóðarauður",  "national wealth",   "kk"),
        ("hagkerfið",    "the economy",       "hk"),
        ("hagkerfi",     "economy",           "hk"),
        ("verðbólga",    "inflation",         "kvk"),
        ("ávöxtun",      "return / yield",    "kvk"),
        ("fjárfesting",  "investment",        "kvk"),
        ("hlutabréf",    "share / stock",     "hk"),
        ("gjaldmiðill",  "currency",          "kk"),
        ("greiðslumiðill","payment method",   "kk"),
        ("kreditkort",   "credit card",       "hk"),
        ("debetkort",    "debit card",        "hk"),
        ("reikningur",   "account / invoice", "kk"),
        ("lánamaður",    "lender",            "kk"),
        ("skuldari",     "borrower",          "kk"),
        ("lánasamningur","loan contract",     "kk"),
        ("trygging",     "insurance",         "kvk"),
        ("skattstofn",   "tax base",          "kk"),
        # ── Modern social / culture ──
        ("samfélagsmiðlar","social media",    "kk"),
        ("áhrifamaður",  "influencer",        "kk"),
        ("straumur",     "stream / current",  "kk"),
        ("dreifir",      "broadcaster",       "kk"),
        ("áskrift",      "subscription",      "kvk"),
        ("innihald",     "content",           "hk"),
        ("merki",        "brand / logo",      "hk"),
        ("auglýsing",    "advertisement",     "kvk"),
        ("smáauglýsing", "micro-ad",          "kvk"),
        ("netgeymir",    "cloud storage",     "kk"),
        ("póst",         "post (social med.)","kk"),
        ("efnilegur",    "substantial (adj)", "kk"),
        ("smárit",       "blog",              "hk"),
        ("leikjatölva",  "gaming computer",   "kvk"),
        ("rafrænn",      "electronic (adj.)", "kk"),
        ("stafrænn",     "digital (adj.)",    "kk"),
        ("gagnvirkt",    "interactive",       "hk"),
        ("þráðbundið",   "wired",             "hk"),
        ("afrita",       "to copy",           "so"),
        ("geyma",        "to store",          "so"),
    ],

    "Sagnir": [
        # ── Motion ──
        ("fara",         "to go",             "so"),
        ("koma",         "to come",           "so"),
        ("hlaupa",       "to run",            "so"),
        ("ganga",        "to walk",           "so"),
        ("ríða",         "to ride",           "so"),
        ("fljúga",       "to fly",            "so"),
        ("synda",        "to swim",           "so"),
        ("klifra",       "to climb",          "so"),
        ("detta",        "to fall",           "so"),
        ("stökkva",      "to jump",           "so"),
        ("skreiða",      "to glide",          "so"),
        ("renna",        "to run (water)",    "so"),
        ("taka",         "to take",           "so"),
        ("bera",         "to carry",          "so"),
        ("draga",        "to drag / pull",    "so"),
        ("ýta",          "to push",           "so"),
        ("skila",        "to return / deliver","so"),
        ("senda",        "to send",           "so"),
        ("koma",         "to come",           "so"),
        # ── Cognition / Communication ──
        ("segja",        "to say / tell",     "so"),
        ("tala",         "to speak / talk",   "so"),
        ("spyrja",       "to ask",            "so"),
        ("svara",        "to answer",         "so"),
        ("hlusta",       "to listen",         "so"),
        ("heyra",        "to hear",           "so"),
        ("sjá",          "to see",            "so"),
        ("skoða",        "to examine / view", "so"),
        ("lesa",         "to read",           "so"),
        ("skrifa",       "to write",          "so"),
        ("hugsa",        "to think",          "so"),
        ("teikna",       "to draw",           "so"),
        ("reikna",       "to calculate",      "so"),
        ("læra",         "to learn",          "so"),
        ("kenna",        "to teach / feel",   "so"),
        ("skilja",       "to understand",     "so"),
        ("vita",         "to know",           "so"),
        ("muna",         "to remember",       "so"),
        ("gleyma",       "to forget",         "so"),
        ("ímynda",       "to imagine",        "so"),
        ("dreyma",       "to dream",          "so"),
        ("finna",        "to find / feel",    "so"),
        ("vita",         "to know",           "so"),
        ("trúa",         "to believe",        "so"),
        ("efast",        "to doubt",          "so"),
        ("geta",         "to be able to",     "so"),
        ("vilja",        "to want",           "so"),
        ("þurfa",        "to need",           "so"),
        ("kunna",        "to know how",       "so"),
        # ── Daily life ──
        ("vera",         "to be",             "so"),
        ("eiga",         "to have / own",     "so"),
        ("hafa",         "to have",           "so"),
        ("gefa",         "to give",           "so"),
        ("fá",           "to get / receive",  "so"),
        ("kaupa",        "to buy",            "so"),
        ("selja",        "to sell",           "so"),
        ("borga",        "to pay",            "so"),
        ("vinna",        "to work / win",     "so"),
        ("vinna",        "to earn",           "so"),
        ("nota",         "to use",            "so"),
        ("opna",         "to open",           "so"),
        ("loka",         "to close",          "so"),
        ("hlusta",       "to listen",         "so"),
        ("sjá",          "to see",            "so"),
        ("búa",          "to live / prepare", "so"),
        ("sofa",         "to sleep",          "so"),
        ("sofna",        "to fall asleep",    "so"),
        ("vakna",        "to wake up",        "so"),
        ("borða",        "to eat",            "so"),
        ("drekka",       "to drink",          "so"),
        ("elda",         "to cook",           "so"),
        ("þvo",          "to wash",           "so"),
        ("þurrkа",       "to dry",            "so"),
        ("klæðast",      "to dress",          "so"),
        ("raka",         "to shave",          "so"),
        ("bursta",       "to brush",          "so"),
        ("þvo",          "to wash",           "so"),
        ("baka",         "to bake",           "so"),
        ("steikja",      "to fry / roast",    "so"),
        ("sjóða",        "to boil",           "so"),
        ("smakka",       "to taste",          "so"),
        ("þvo",          "to do laundry",     "so"),
        # ── Social ──
        ("hitta",        "to meet",           "so"),
        ("mæta",         "to meet / attend",  "so"),
        ("kynna",        "to introduce",      "so"),
        ("bjóða",        "to invite / offer", "so"),
        ("sækja",        "to fetch / apply",  "so"),
        ("heimsækja",    "to visit",          "so"),
        ("þakka",        "to thank",          "so"),
        ("biðjast",      "to apologize",      "so"),
        ("gráta",        "to cry",            "so"),
        ("hlæja",        "to laugh",          "so"),
        ("brosа",        "to smile",          "so"),
        ("elska",        "to love",           "so"),
        ("hata",         "to hate",           "so"),
        ("þola",         "to tolerate",       "so"),
        ("gleðjast",     "to be glad",        "so"),
        ("syrgjast",     "to grieve",         "so"),
        ("óttast",       "to fear",           "so"),
        ("kvíða",        "to dread / worry",  "so"),
        ("treysta",      "to trust",          "so"),
        ("deila",        "to share / argue",  "so"),
        ("semja",        "to agree / compose","so"),
        ("samþykkja",    "to agree / approve","so"),
        ("hafna",        "to reject",         "so"),
        ("berjast",      "to fight",          "so"),
        ("sigra",        "to win / conquer",  "so"),
        ("tapa",         "to lose",           "so"),
        # ── Physical actions ──
        ("slá",          "to hit / beat",     "so"),
        ("sparka",       "to kick",           "so"),
        ("kasta",        "to throw",          "so"),
        ("grípa",        "to grab / catch",   "so"),
        ("halda",        "to hold / think",   "so"),
        ("setja",        "to set / put",      "so"),
        ("leggja",       "to lay / put",      "so"),
        ("taka",         "to take",           "so"),
        ("lyfta",        "to lift",           "so"),
        ("standa",       "to stand",          "so"),
        ("sitja",        "to sit",            "so"),
        ("liggja",       "to lie down",       "so"),
        ("snúa",         "to turn",           "so"),
        ("opna",         "to open",           "so"),
        ("loka",         "to close / lock",   "so"),
        ("slökkva",      "to turn off",       "so"),
        ("kveikja",      "to light / turn on","so"),
        ("sprengja",     "to blow up",        "so"),
        ("brjóta",       "to break",          "so"),
        ("gera",         "to make / do",      "so"),
        ("búa til",      "to create",         "so"),
        ("eyðileggja",   "to destroy",        "so"),
        ("laga",         "to fix / repair",   "so"),
        ("hreinsa",      "to clean",          "so"),
        ("sopa",         "to sweep",          "so"),
        ("þrífa",        "to clean",          "so"),
        ("mála",         "to paint",          "so"),
        ("skreyta",      "to decorate",       "so"),
        # ── Work / Creation ──
        ("vinna",        "to work",           "so"),
        ("reyna",        "to try",            "so"),
        ("ljúka",        "to finish",         "so"),
        ("byrja",        "to begin / start",  "so"),
        ("halda",        "to continue",       "so"),
        ("stoppa",       "to stop",           "so"),
        ("breyta",       "to change",         "so"),
        ("bæta",         "to improve",        "so"),
        ("mæla",         "to measure",        "so"),
        ("reikna",       "to calculate",      "so"),
        ("skipuleggja",  "to plan",           "so"),
        ("ráða",         "to advise / hire",  "so"),
        ("fræða",        "to educate",        "so"),
        ("þróa",         "to develop",        "so"),
        ("rannsaka",     "to research",       "so"),
        ("uppgötva",     "to discover",       "so"),
        ("finna upp",    "to invent",         "so"),
        ("birta",        "to publish",        "so"),
        ("sýna",         "to show",           "so"),
        ("geyma",        "to store",          "so"),
        ("flytja",       "to move / transport","so"),
        ("kynna til sögunnar","to introduce", "so"),
        ("keyra",        "to drive",          "so"),
        ("stjórna",      "to manage / steer", "so"),
        ("skipuleggja",  "to organise",       "so"),
        ("áætla",        "to estimate / plan","so"),
        ("ákveða",       "to decide",         "so"),
        ("velja",        "to choose",         "so"),
        ("hafna",        "to refuse",         "so"),
        ("samþykkja",    "to accept",         "so"),
        ("ganga í",      "to join",           "so"),
        ("yfirgefa",     "to leave / abandon","so"),
        # ── Nature / Environment ──
        ("vaxa",         "to grow",           "so"),
        ("deyja",        "to die",            "so"),
        ("lifa",         "to live",           "so"),
        ("ala",          "to breed / give birth","so"),
        ("nærast",       "to feed oneself",   "so"),
        ("veiða",        "to hunt / fish",    "so"),
        ("leika",        "to play",           "so"),
        ("syngja",       "to sing",           "so"),
        ("dansa",        "to dance",          "so"),
        ("spila",        "to play (music)",   "so"),
        ("hlusta",       "to listen",         "so"),
        ("skoða",        "to view / look at", "so"),
        ("ljósmynda",    "to photograph",     "so"),
        ("mæla",         "to measure",        "so"),
        ("horfa",        "to watch",          "so"),
        ("þiggja",       "to receive / accept","so"),
        ("biðja",        "to pray / ask",     "so"),
        ("bíða",         "to wait",           "so"),
        ("standa",       "to stand",          "so"),
        ("hlaða",        "to load",           "so"),
        ("ræða",         "to discuss",        "so"),
        ("bera",         "to carry",          "so"),
        ("dreifa",       "to distribute",     "so"),
        ("skipta",       "to divide / change","so"),
        ("sameina",      "to unite",          "so"),
        ("aðskilja",     "to separate",       "so"),
        ("raða",         "to sort / arrange", "so"),
        ("para",         "to pair",           "so"),
        ("blanda",       "to mix",            "so"),
        ("setja saman",  "to assemble",       "so"),
        ("taka í sundur","to disassemble",    "so"),
        ("geyma",        "to store / keep",   "so"),
        ("nota",         "to use",            "so"),
        ("skila",        "to return",         "so"),
        ("borga",        "to pay",            "so"),
        ("kaupa",        "to buy / purchase", "so"),
        ("sækja",        "to fetch",          "so"),
        ("flytja",       "to transport",      "so"),
        ("afhenda",      "to deliver",        "so"),
        ("taka við",     "to receive",        "so"),
        ("kvarta",       "to complain",       "so"),
        ("þakka",        "to thank",          "so"),
        ("fagna",        "to rejoice / welcome","so"),
        ("villa",        "to make a mistake", "so"),
        ("laga",         "to fix",            "so"),
        ("æfa",          "to practise",       "so"),
        ("fara í gegnum","to go through",     "so"),
    ],

    "Matur": [
        # ── Bread / Grains ──
        ("brauð",        "bread",             "hk"),
        ("rúgbrauð",     "rye bread",         "hk"),
        ("flatbrauð",    "flatbread",         "hk"),
        ("kex",          "cracker / biscuit", "hk"),
        ("hafragrautur", "porridge / oatmeal","kk"),
        ("hrísgrjón",    "rice",              "hk"),
        ("pasta",        "pasta",             "hk"),
        ("maís",         "corn / maize",      "kk"),
        ("hveiti",       "wheat / flour",     "hk"),
        ("rúgmjöl",      "rye flour",         "hk"),
        ("korn",         "grain / cereal",    "hk"),
        ("haframjöl",    "oat flour",         "hk"),
        # ── Vegetables ──
        ("kartafla",     "potato",            "kvk"),
        ("rauðrófа",     "beetroot",          "kvk"),
        ("gulrót",       "carrot",            "kvk"),
        ("laukur",       "onion",             "kk"),
        ("hvítlaukur",   "garlic",            "kk"),
        ("tómatur",      "tomato",            "kk"),
        ("gúrka",        "cucumber",          "kvk"),
        ("paprika",      "bell pepper",       "kvk"),
        ("salat",        "salad / lettuce",   "hk"),
        ("sveppur",      "mushroom",          "kk"),
        ("blómkál",      "cauliflower",       "hk"),
        ("brokkál",      "broccoli",          "hk"),
        ("spínat",       "spinach",           "hk"),
        ("baun",         "bean",              "kvk"),
        ("ert",          "pea",               "kvk"),
        ("grænkál",      "kale",              "hk"),
        ("kál",          "cabbage",           "hk"),
        ("spergilkál",   "asparagus",         "hk"),
        ("sellerí",      "celery",            "hk"),
        ("fennikál",     "fennel",            "hk"),
        ("reddíkur",     "radish",            "kk"),
        ("kóríander",    "coriander",         "kk"),
        ("dill",         "dill",              "hk"),
        ("steinselja",   "parsley",           "kvk"),
        ("lárviður",     "bay leaf",          "kk"),
        # ── Fruit ──
        ("epli",         "apple",             "hk"),
        ("appelsína",    "orange",            "kvk"),
        ("banani",       "banana",            "kk"),
        ("jarðarber",    "strawberry",        "hk"),
        ("bláber",       "blueberry",         "hk"),
        ("vínber",       "grape",             "hk"),
        ("kirsuber",     "cherry",            "hk"),
        ("ferskja",      "peach",             "kvk"),
        ("mangó",        "mango",             "hk"),
        ("ananas",       "pineapple",         "kk"),
        ("kíví",         "kiwi",              "hk"),
        ("melóna",       "melon",             "kvk"),
        ("pera",         "pear",              "kvk"),
        ("plóma",        "plum",              "kvk"),
        ("sítróna",      "lemon",             "kvk"),
        ("límóna",       "lime",              "kvk"),
        ("papaya",       "papaya",            "kvk"),
        ("avókadó",      "avocado",           "hk"),
        ("kókoshnet",    "coconut",           "hk"),
        ("vatnmelóna",   "watermelon",        "kvk"),
        ("þyrnir",       "berry (wild)",      "kk"),
        ("berjatré",     "berry bush",        "hk"),
        ("hrísber",      "currant",           "hk"),
        # ── Meat / Protein ──
        ("kjöt",         "meat",              "hk"),
        ("lambakjöt",    "lamb meat",         "hk"),
        ("nautakjöt",    "beef",              "hk"),
        ("svínakjöt",    "pork",              "hk"),
        ("kjúklingur",   "chicken",           "kk"),
        ("kalkúnn",      "turkey",            "kk"),
        ("andarbringa",  "duck breast",       "kvk"),
        ("villt",        "game meat",         "hk"),
        ("pylsa",        "sausage",           "kvk"),
        ("bollusteik",   "meatball",          "kvk"),
        ("skinka",       "ham",               "kvk"),
        ("beikon",       "bacon",             "hk"),
        ("lifur",        "liver (food)",      "kvk"),
        ("nýra",         "kidney (food)",     "hk"),
        # ── Seafood ──
        ("lax",          "salmon",            "kk"),
        ("þorskur",      "cod",               "kk"),
        ("síld",         "herring",           "kvk"),
        ("ufsi",         "saithe",            "kk"),
        ("ýsa",          "haddock",           "kvk"),
        ("karfi",        "redfish",           "kk"),
        ("rækja",        "shrimp",            "kvk"),
        ("humar",        "lobster",           "kk"),
        ("krabbi",       "crab",              "kk"),
        ("kóng",         "scallop",           "kk"),
        ("þari",         "seaweed",           "kk"),
        # ── Dairy / Eggs ──
        ("egg",          "egg",               "hk"),
        ("mjólk",        "milk",              "kvk"),
        ("skyr",         "skyr (Icel. dairy)","hk"),
        ("rjómi",        "cream",             "kk"),
        ("smjör",        "butter",            "hk"),
        ("ost",          "cheese",            "kk"),
        ("ostur",        "cheese (colloq.)",  "kk"),
        ("jógúrt",       "yoghurt",           "hk"),
        # ── Drinks ──
        ("vatn",         "water",             "hk"),
        ("kaffi",        "coffee",            "hk"),
        ("te",           "tea",               "hk"),
        ("safi",         "juice",             "kk"),
        ("bjór",         "beer",              "kk"),
        ("vín",          "wine",              "hk"),
        ("appelsínusafi","orange juice",      "kk"),
        ("gosdrykkur",   "soda / fizzy drink","kk"),
        ("heitt kakó",   "hot cocoa",         "hk"),
        ("sítrónuvatn",  "lemon water",       "hk"),
        ("brennivín",    "Icelandic schnapps","hk"),
        ("lemonade",     "lemonade",          "hk"),
        # ── Sweets / Desserts ──
        ("sykur",        "sugar",             "kk"),
        ("hunang",       "honey",             "hk"),
        ("súkkulaði",    "chocolate",         "hk"),
        ("konfekt",      "sweets / candy",    "hk"),
        ("kaka",         "cake",              "kvk"),
        ("terta",        "tart / cake",       "kvk"),
        ("pönnukaka",    "pancake",           "kvk"),
        ("mafín",        "muffin",            "kk"),
        ("kex",          "cookie",            "hk"),
        ("ís",           "ice cream",         "kk"),
        ("skúffukaka",   "tray cake",         "kvk"),
        ("vöfflur",      "waffle (pl.)",      "kvk"),
        ("kleina",       "twisted doughnut",  "kvk"),
        ("vínarbrauð",   "Danish pastry",     "hk"),
        # ── Herbs / Spices / Condiments ──
        ("salt",         "salt",              "hk"),
        ("pipar",        "pepper",            "kk"),
        ("edik",         "vinegar",           "hk"),
        ("sinnep",       "mustard",           "hk"),
        ("ketsap",       "ketchup",           "hk"),
        ("majónes",      "mayonnaise",        "hk"),
        ("sósa",         "sauce",             "kvk"),
        ("olía",         "oil",               "kvk"),
        ("ólífuolía",    "olive oil",         "kvk"),
        ("hvítlauksolía","garlic oil",        "kvk"),
        ("sojasósa",     "soy sauce",         "kvk"),
        ("kúmen",        "caraway (spice)",   "hk"),
        ("lórber",       "bay leaf (spice)",  "hk"),
        ("kanill",       "cinnamon",          "kk"),
        ("múskat",       "nutmeg",            "hk"),
        ("chilli",       "chilli",            "hk"),
        ("túrmerik",     "turmeric",          "hk"),
        # ── Meals / Dishes ──
        ("máltíð",       "meal",              "kvk"),
        ("morgunmatur",  "breakfast",         "kk"),
        ("hádegismatur", "lunch",             "kk"),
        ("kvöldmatur",   "dinner / supper",   "kk"),
        ("samloka",      "sandwich",          "kvk"),
        ("súpa",         "soup",              "kvk"),
        ("salat",        "salad",             "hk"),
        ("graut",        "porridge",          "kk"),
        ("grautur",      "porridge / gruel",  "kk"),
        ("pítsa",        "pizza",             "kvk"),
        ("hamborgari",   "hamburger",         "kk"),
        ("taco",         "taco",              "hk"),
        ("sushi",        "sushi",             "hk"),
        ("pasta",        "pasta dish",        "hk"),
    ],

    "Náttúra": [
        # ── Earth / Landscape ──
        ("jörð",         "earth / soil",      "kvk"),
        ("land",         "land",              "hk"),
        ("strönd",       "coast / shore",     "kvk"),
        ("fjörður",      "fjord",             "kk"),
        ("fjall",        "mountain",          "hk"),
        ("dalur",        "valley",            "kk"),
        ("heiði",        "heath / highland",  "kvk"),
        ("mýri",         "marsh / bog",       "kvk"),
        ("skógur",       "forest",            "kk"),
        ("tré",          "tree",              "hk"),
        ("grein",        "branch",            "kvk"),
        ("lauf",         "leaf",              "hk"),
        ("gras",         "grass",             "hk"),
        ("blóm",         "flower",            "hk"),
        ("mosi",         "moss",              "kk"),
        ("steinn",       "stone / rock",      "kk"),
        ("sandur",       "sand",              "kk"),
        ("klif",         "cliff",             "hk"),
        ("gígur",        "crater",            "kk"),
        ("hraun",        "lava field",        "hk"),
        ("eldfjall",     "volcano",           "hk"),
        ("jarðskjálfti", "earthquake",        "kk"),
        ("slétta",       "plain / flatland",  "kvk"),
        ("melar",        "gravel field",      "kk"),
        ("hnjúkur",      "peak / summit",     "kk"),
        ("hlíð",         "hillside",          "kvk"),
        ("urriðafoss",   "rapids",            "kk"),
        # ── Water ──
        ("sjór",         "sea / ocean",       "kk"),
        ("haf",          "ocean",             "hk"),
        ("ár",           "river",             "kvk"),
        ("lón",          "lagoon / pond",     "hk"),
        ("stöðuvatn",    "lake",              "hk"),
        ("fossur",       "waterfall",         "kk"),
        ("ísbreiða",     "ice sheet",         "kvk"),
        ("jökull",       "glacier",           "kk"),
        ("ból",          "pool / hollow",     "hk"),
        ("geyser",       "geyser",            "kk"),
        ("laug",         "hot spring",        "kvk"),
        ("hverir",       "hot springs (pl.)", "kk"),
        ("ísinn",        "the ice",           "kk"),
        ("ís",           "ice",               "kk"),
        # ── Sky / Weather ──
        ("himinn",       "sky / heaven",      "kk"),
        ("sól",          "sun",               "kvk"),
        ("tungl",        "moon",              "hk"),
        ("stjarna",      "star",              "kvk"),
        ("ský",          "cloud",             "hk"),
        ("vindur",       "wind",              "kk"),
        ("rigning",      "rain",              "kvk"),
        ("snjór",        "snow",              "kk"),
        ("hagl",         "hail",              "hk"),
        ("þoka",         "fog / mist",        "kvk"),
        ("stormur",      "storm",             "kk"),
        ("þruma",        "thunder",           "kvk"),
        ("elding",       "lightning",         "kvk"),
        ("norðurljós",   "northern lights",   "hk"),
        ("regnbogi",     "rainbow",           "kk"),
        ("hitabylgja",   "heat wave",         "kvk"),
        ("veðrið",       "the weather",       "hk"),
        ("veður",        "weather",           "hk"),
        ("loftslagi",    "climate",           "hk"),
        ("loftslag",     "climate",           "hk"),
        ("veturinn",     "the winter",        "kk"),
        ("vetur",        "winter",            "kk"),
        ("sumar",        "summer",            "hk"),
        ("vor",          "spring",            "hk"),
        ("haust",        "autumn",            "hk"),
        # ── Plants / Flora ──
        ("birkitré",     "birch tree",        "hk"),
        ("furu",         "pine tree",         "kvk"),
        ("greni",        "spruce",            "hk"),
        ("gulur",        "dandelion",         "kk"),
        ("blómaþúfa",    "flower cluster",    "kvk"),
        ("þistill",      "thistle",           "kk"),
        ("lyng",         "heather",           "hk"),
        ("hundasúra",    "sorrel",            "kvk"),
        ("grasker",      "pumpkin",           "hk"),
        ("epaltré",      "apple tree",        "hk"),
        ("þara",         "seaweed (edible)",  "kk"),
        ("sveppur",      "mushroom / fungus", "kk"),
        ("mygla",        "mould",             "kvk"),
        # ── Elements / Materials ──
        ("eldur",        "fire",              "kk"),
        ("vatn",         "water",             "hk"),
        ("loft",         "air",               "hk"),
        ("jarðvegur",    "soil / earth",      "kk"),
        ("járn",         "iron",              "hk"),
        ("gull",         "gold",              "hk"),
        ("silfur",       "silver",            "hk"),
        ("kopar",        "copper",            "kk"),
        ("stál",         "steel",             "hk"),
        ("ál",           "aluminium",         "hk"),
        ("kol",          "coal",              "hk"),
        ("olía",         "oil",               "kvk"),
        ("gas",          "gas",               "hk"),
        ("marmari",      "marble",            "kk"),
        ("efni",         "material / substance","hk"),
        ("kísill",       "silicon",           "kk"),
        ("kalksteinn",   "limestone",         "kk"),
        ("þara",         "seaweed",           "kk"),
    ],

    "Líkami": [
        ("höfuð",        "head",              "hk"),
        ("háls",         "neck / throat",     "kk"),
        ("öxl",          "shoulder",          "kvk"),
        ("bringa",       "chest",             "kvk"),
        ("brjóst",       "breast / chest",    "hk"),
        ("magi",         "stomach",           "kk"),
        ("mjóbak",       "lower back",        "hk"),
        ("bak",          "back",              "hk"),
        ("handleggur",   "arm",               "kk"),
        ("olnbogi",      "elbow",             "kk"),
        ("úlnliður",     "wrist",             "kk"),
        ("hönd",         "hand",              "kvk"),
        ("fingur",       "finger",            "kk"),
        ("þumalfingur",  "thumb",             "kk"),
        ("fótur",        "leg / foot",        "kk"),
        ("læri",         "thigh",             "hk"),
        ("kné",          "knee",              "hk"),
        ("leggur",       "shin / lower leg",  "kk"),
        ("ökkli",        "ankle",             "kk"),
        ("tá",           "toe",               "kvk"),
        ("nef",          "nose",              "hk"),
        ("eyra",         "ear",               "hk"),
        ("auga",         "eye",               "hk"),
        ("munnur",       "mouth",             "kk"),
        ("vör",          "lip",               "kvk"),
        ("tunga",        "tongue",            "kvk"),
        ("tennur",       "teeth",             "kvk"),
        ("tönn",         "tooth",             "kvk"),
        ("kinn",         "cheek",             "kvk"),
        ("haka",         "chin",              "kvk"),
        ("enni",         "forehead",          "hk"),
        ("gaumur",       "palate",            "kk"),
        ("hár",          "hair",              "hk"),
        ("húð",          "skin",              "kvk"),
        ("neglur",       "nails (pl.)",       "kvk"),
        ("nögl",         "nail",              "kvk"),
        ("æð",           "vein",              "kvk"),
        ("liður",        "joint",             "kk"),
        ("bein",         "bone",              "hk"),
        ("vöðvi",        "muscle",            "kk"),
        ("hjarta",       "heart",             "hk"),
        ("lunga",        "lung",              "hk"),
        ("lifur",        "liver",             "kvk"),
        ("nýra",         "kidney",            "hk"),
        ("magi",         "stomach",           "kk"),
        ("þarmur",       "intestine",         "kk"),
        ("blóð",         "blood",             "hk"),
        ("taugur",       "nerve",             "kvk"),
        ("heili",        "brain",             "kk"),
        ("gall",         "bile / gall",       "hk"),
        ("lifur",        "liver",             "kvk"),
        ("bukveggi",     "abdominal wall",    "kk"),
        ("hryggur",      "spine",             "kk"),
        ("mjóbak",       "lower back",        "hk"),
        ("ristill",      "rectum",            "kk"),
        ("bristur",      "pancreas",          "kk"),
        ("milta",        "spleen",            "kvk"),
        ("þvaghvolf",    "bladder",           "hk"),
    ],

    "Klæði": [
        # ── Upper body ──
        ("skyrta",       "shirt",             "kvk"),
        ("peysa",        "sweater / jumper",  "kvk"),
        ("jakki",        "jacket",            "kk"),
        ("yfirjakki",    "overcoat",          "kk"),
        ("boli",         "T-shirt",           "kk"),
        ("bolur",        "jumper / top",      "kk"),
        ("blússa",       "blouse",            "kvk"),
        ("vestur",       "waistcoat / vest",  "kk"),
        ("búningur",     "uniform / suit",    "kk"),
        ("einlitur",     "plain (adj.)",      "kk"),
        # ── Lower body ──
        ("buxur",        "trousers / pants",  "kvk"),
        ("stuttbuxur",   "shorts",            "kvk"),
        ("gallabuxur",   "jeans",             "kvk"),
        ("kjóll",        "dress",             "kk"),
        ("pils",         "skirt",             "hk"),
        ("gallar",       "overalls",          "kk"),
        # ── Feet ──
        ("skór",         "shoe",              "kk"),
        ("stígvél",      "boot",              "hk"),
        ("sandali",      "sandal",            "kk"),
        ("inniskór",     "indoor shoes",      "kk"),
        ("sokkur",       "sock",              "kk"),
        ("leggings",     "leggings",          "hk"),
        # ── Head / Accessories ──
        ("hattur",       "hat",               "kk"),
        ("húfa",         "beanie / cap",      "kvk"),
        ("hanski",       "glove",             "kk"),
        ("trefill",      "scarf",             "kk"),
        ("belti",        "belt",              "hk"),
        ("kragi",        "collar",            "kk"),
        ("ermi",         "sleeve",            "kvk"),
        ("slips",        "tie / necktie",     "hk"),
        ("hárband",      "hairband",          "hk"),
        # ── Underwear ──
        ("undirpeysa",   "thermal undershirt","kvk"),
        ("brók",         "underpants",        "kvk"),
        ("brjóstahaldari","bra",              "kk"),
        # ── Swimwear / Sport ──
        ("sundföt",      "swimwear",          "hk"),
        ("íþróttabúningur","sportswear",      "kk"),
        ("hjálmur",      "helmet",            "kk"),
        ("öryggisjakki", "safety jacket",     "kk"),
        # ── Materials / Care ──
        ("efni",         "fabric / material", "hk"),
        ("silki",        "silk",              "hk"),
        ("ull",          "wool",              "kvk"),
        ("bómull",       "cotton",            "kvk"),
        ("leður",        "leather",           "hk"),
        ("plast",        "plastic",           "hk"),
        ("þvottur",      "laundry",           "kk"),
    ],
}


# ──────────────────────────────────────────────────────────────────────────────
# Merge extra words
# ──────────────────────────────────────────────────────────────────────────────
for _extra in (EXTRA, EXTRA2, EXTRA3, EXTRA4):
    for _cat, _entries in _extra.items():
        if _cat in WORDS:
            WORDS[_cat].extend(_entries)
        else:
            WORDS[_cat] = _entries


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    categories = list(WORDS.keys())
    bank = {cat: [] for cat in categories}
    total = 0
    skipped = 0

    for cat, entries in WORDS.items():
        seen_bases = set()
        for idx, (lemma, translation, kyn) in enumerate(entries):
            key = (lemma, kyn)
            if key in seen_bases:
                continue
            seen_bases.add(key)

            entry = build_entry(lemma, translation, kyn, cat, idx)
            if entry is None:
                skipped += 1
                print(f"  SKIP  {lemma:25s}  ({kyn})  [{cat}]", file=sys.stderr)
                continue
            bank[cat].append(entry)
            total += 1

        print(f"  {cat:12s}: {len(bank[cat])} words", file=sys.stderr)

    print(f"\nTotal: {total} entries, {skipped} skipped", file=sys.stderr)

    out = {
        "categories": categories,
        "words": bank,
    }

    # write output
    script_dir = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(script_dir, "..", "Refur", "words.json")
    out_path = os.path.normpath(out_path)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print(f"\nWrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
