"""Fourth wave — ultra-simple words to clear the 2000 threshold."""

EXTRA4 = {
    "Nöfn": [
        ("barn",         "child",             "hk"),
        ("fjöldi",       "number / multitude","kk"),
        ("hvíld",        "rest",              "kvk"),
        ("íbúð",         "apartment",         "kvk"),
        ("kast",         "throw / cast",      "hk"),
        ("kvöl",         "agony / torment",   "kvk"),
        ("lyst",         "appetite / desire", "kvk"),
        ("náungi",       "neighbor",          "kk"),
        ("snilld",       "brilliance",        "kvk"),
        ("svefn",        "sleep",             "kk"),
        ("þræll",        "thrall / slave",    "kk"),
        ("gleði",        "joy / happiness",   "kvk"),
        ("skaði",        "damage / harm",     "kk"),
        ("góðvild",      "goodwill",          "kvk"),
        ("áhugi",        "interest",          "kk"),
        ("munur",        "difference",        "kk"),
        ("flóði",        "flood",             "kk"),
        ("bragur",       "style / tune",      "kk"),
        ("skuggi",       "shadow / shade",    "kk"),
        ("lof",          "praise / ceiling",  "hk"),
        ("slæmur",       "bad (nom.)",        "kk"),
        ("stund",        "hour / moment",     "kvk"),
        ("merking",      "meaning",           "kvk"),
        ("háttur",       "way / manner",      "kk"),
        ("rof",          "break / interference","hk"),
        ("endi",         "end / edge",        "kk"),
        ("heimur",       "world",             "kk"),
        ("hlý",          "warmth",            "hk"),
        ("dæmi",         "example",           "hk"),
        ("bót",          "improvement / remedy","kvk"),
        ("hlaupur",      "run / race",        "kk"),
        ("þúsund",       "thousand",          "hk"),
        ("hundrað",      "hundred",           "hk"),
        ("tíund",        "tenth / tithe",     "kvk"),
        ("tug",          "ten / decade",      "kk"),
        ("kaffi",        "coffee",            "hk"),
        ("boð",          "message / invitation","hk"),
        ("boðun",        "summons",           "kvk"),
        ("þjóðveldið",   "the republic",      "hk"),
        ("þjóðveldi",    "republic",          "hk"),
        ("ráðgjöf",      "counselling",       "kvk"),
        ("upplýsing",    "information",       "kvk"),
        ("heilun",       "healing",           "kvk"),
        ("mótmæli",      "protest",           "hk"),
        ("þvægi",        "dilution",          "hk"),
        ("hlutskipti",   "fate / share",      "hk"),
        ("auður",        "wealth",            "kk"),
        ("fátækt",       "poverty",           "kvk"),
        ("ótti",         "fear",              "kk"),
        ("gremja",       "irritation",        "kvk"),
    ],

    "Sagnir": [
        ("brenna",       "to burn",           "so"),
        ("þurrka",       "to dry",            "so"),
        ("flakka",       "to wander",         "so"),
        ("kynja",        "to sort by type",   "so"),
        ("hlypa",        "to gallop",         "so"),
        ("kveikjast",    "to ignite",         "so"),
        ("þenja",        "to stretch out",    "so"),
        ("lyfta",        "to elevate",        "so"),
        ("smíða",        "to craft / build",  "so"),
        ("þjóna",        "to minister",       "so"),
        ("minnka",       "to diminish",       "so"),
        ("stækka",       "to grow larger",    "so"),
        ("breikka",      "to broaden",        "so"),
        ("þorna",        "to dry out",        "so"),
        ("kólna",        "to cool",           "so"),
        ("harðna",       "to harden",         "so"),
        ("mýkja",        "to soften",         "so"),
        ("grilla",       "to grill",          "so"),
        ("baka",         "to bake",           "so"),
        ("raða",         "to arrange",        "so"),
        ("leggja",       "to place",          "so"),
        ("slá",          "to strike",         "so"),
        ("skilja",       "to understand",     "so"),
        ("sópa",         "to sweep",          "so"),
        ("prenta",       "to print",          "so"),
    ],

    "Hlutir": [
        ("flögur",       "flakes / tiles",    "kvk"),
        ("kjöl",         "keel / core",       "kk"),
        ("höfuðstóll",   "capital (finance)", "kk"),
        ("mótmælari",    "protestor",         "kk"),
        ("ör",           "arrow",             "kvk"),
        ("spjót",        "spear",             "hk"),
        ("skjöldur",     "shield",            "kk"),
        ("sverð",        "sword",             "hk"),
        ("bogi",         "bow (archery)",     "kk"),
        ("skálinn",      "the scale",         "kk"),
    ],

    "Náttúra": [
        ("gufa",         "steam / vapour",    "kvk"),
        ("eldur",        "fire",              "kk"),
        ("aska",         "ash",               "kvk"),
        ("íshellir",     "ice cave",          "kk"),
        ("keldur",       "spring / marsh",    "kk"),
        ("keflavík",     "harbour bay",       "kvk"),
        ("hólkur",       "pipe / sleeve",     "kk"),
        ("þúsundfaldur", "thousandfold",      "kk"),
        ("heimi",        "world / home",      "kk"),
        ("klæðningur",   "cladding / coating","kk"),
    ],
}
