"""
Extra word entries to supplement build_wordbank.py.
Merged into WORDS before building.
"""

EXTRA = {
    "Nöfn": [
        # ── More people / occupations ──
        ("útlendingur",  "foreigner",         "kk"),
        ("ferðamaður",   "traveler / tourist","kk"),
        ("fræðimaður",   "scholar",           "kk"),
        ("starfsmaður",  "employee",          "kk"),
        ("rannsakandi",  "researcher",        "kk"),
        ("ráðgjafi",     "advisor",           "kk"),
        ("verkstjóri",   "foreman",           "kk"),
        ("málari",       "painter",           "kk"),
        ("múrari",       "mason",             "kk"),
        ("sjúkraþjálfari","physiotherapist",  "kk"),
        ("leikmaður",    "player",            "kk"),
        ("meðlimur",     "member",            "kk"),
        ("mótmælandi",   "protester",         "kk"),
        ("trúmaður",     "believer",          "kk"),
        ("félagi",       "comrade / partner", "kk"),
        ("ráðherra",     "minister",          "kk"),
        ("alþingismaður","MP / parliamentarian","kk"),
        ("borgarstjóri", "mayor",             "kk"),
        ("framkvæmdastjóri","CEO / director", "kk"),
        ("hluthafi",     "shareholder",       "kk"),
        ("skógarvörður", "forest ranger",     "kk"),
        ("hafnarræðismaður","harbourmaster",  "kk"),
        ("dóttir",       "daughter",          "kvk"),
        ("móðir",        "mother",            "kvk"),
        ("systir",       "sister",            "kvk"),
        # ── Society / abstract ──
        ("almenningur",  "the public",        "kk"),
        ("einstaklingur","individual",        "kk"),
        ("fjölskylda",   "family",            "kvk"),
        ("fólk",         "people",            "hk"),
        ("geiri",        "sector / area",     "kk"),
        ("lýðræði",      "democracy",         "hk"),
        ("mannréttindi", "human rights",      "hk"),
        ("samtök",       "organisation",      "hk"),
        ("velferð",      "welfare",           "kvk"),
        ("jafnrétti",    "equality",          "hk"),
        ("samfélag",     "society",           "hk"),
        ("nágrenni",     "neighbourhood",     "hk"),
        ("kvóti",        "quota",             "kk"),
        ("lögregla",     "police",            "kvk"),
        ("stjórnvald",   "authority",         "hk"),
        # ── Abstract nouns ──
        ("aðferð",       "method",            "kvk"),
        ("atburður",     "event",             "kk"),
        ("bakgrunnur",   "background",        "kk"),
        ("bilun",        "failure",           "kvk"),
        ("bylgja",       "wave",              "kvk"),
        ("dagsetning",   "date",              "kvk"),
        ("einkenni",     "symptom / feature", "hk"),
        ("fall",         "fall / case",       "hk"),
        ("form",         "form / shape",      "hk"),
        ("fundur",       "meeting",           "kk"),
        ("gáta",         "puzzle / riddle",   "kvk"),
        ("gisting",      "accommodation",     "kvk"),
        ("grunnur",      "foundation / base", "kk"),
        ("hlutur",       "thing / object",    "kk"),
        ("hlutverk",     "role",              "hk"),
        ("höfuðborg",    "capital city",      "kvk"),
        ("hugtak",       "concept / idea",    "hk"),
        ("íþrótt",       "sport",             "kvk"),
        ("keppni",       "competition",       "kvk"),
        ("kenning",      "theory",            "kvk"),
        ("kynning",      "introduction",      "kvk"),
        ("lag",          "song / layer",      "hk"),
        ("lán",          "luck / loan",       "hk"),
        ("leið",         "way / route",       "kvk"),
        ("listi",        "list",              "kk"),
        ("mál",          "matter / language", "hk"),
        ("markmið",      "goal / objective",  "hk"),
        ("meirihluti",   "majority",          "kk"),
        ("miðlun",       "mediation",         "kvk"),
        ("nám",          "study / learning",  "hk"),
        ("neysla",       "consumption",       "kvk"),
        ("niðurstaða",   "result / outcome",  "kvk"),
        ("nýsköpun",     "innovation",        "kvk"),
        ("pallur",       "platform / podium", "kk"),
        ("rás",          "channel / track",   "kvk"),
        ("samskipti",    "communication",     "hk"),
        ("samtal",       "conversation",      "hk"),
        ("sjúkdómur",    "disease / illness", "kk"),
        ("sjálfræði",    "autonomy",          "hk"),
        ("skipulag",     "organisation",      "hk"),
        ("skrá",         "file / record",     "kvk"),
        ("skýrsla",      "report",            "kvk"),
        ("smíði",        "craft / handiwork", "kvk"),
        ("staðall",      "standard",          "kk"),
        ("stefna",       "policy / direction","kvk"),
        ("stofnun",      "institution",       "kvk"),
        ("stuðningur",   "support",           "kk"),
        ("styrkur",      "strength / grant",  "kk"),
        ("takmörkun",    "limitation",        "kvk"),
        ("tilfinning",   "feeling / emotion", "kvk"),
        ("tillaga",      "proposal",          "kvk"),
        ("þátttaka",     "participation",     "kvk"),
        ("þjálfun",      "training",          "kvk"),
        ("umhverfi",     "environment",       "hk"),
        ("undirbúningur","preparation",       "kk"),
        ("uppbygging",   "development",       "kvk"),
        ("uppruni",      "origin",            "kk"),
        ("viðhald",      "maintenance",       "hk"),
        ("viðskipti",    "business / trade",  "hk"),
        ("virðing",      "respect",           "kvk"),
        ("yfirlit",      "overview",          "hk"),
        ("sérfræðingur", "expert / specialist","kk"),
        ("nýting",       "utilisation",       "kvk"),
        # ── More places ──
        ("framhaldsskóli","secondary school",  "kk"),
        ("heilsugæsla",  "health centre",     "kvk"),
        ("miðbær",       "city centre",       "kk"),
        ("þjóðgarður",   "national park",     "kk"),
        ("samkomuhús",   "community hall",    "hk"),
        ("tjörn",        "pond",              "kvk"),
        ("alþingi",      "parliament",        "hk"),
        ("göngubrú",     "footbridge",        "kvk"),
        ("dagvistun",    "daycare",           "kvk"),
        ("bókabúð",      "bookshop",          "kvk"),
        ("þinghús",      "parliament building","hk"),
        ("útgáfufyrirtæki","publisher",       "hk"),
        ("verslunarmiðstöð","shopping centre","kvk"),
        # ── More everyday concepts ──
        ("hjúskapur",    "marriage",          "kk"),
        ("skilnaður",    "divorce",           "kk"),
        ("samviska",     "conscience",        "kvk"),
        ("hugur",        "mind / spirit",     "kk"),
        ("gæfa",         "luck / fortune",    "kvk"),
        ("hamingja",     "happiness",         "kvk"),
        ("sátt",         "peace / settlement","kvk"),
        ("orka",         "energy",            "kvk"),
        ("þreyta",       "fatigue",           "kvk"),
        ("verkur",       "pain / ache",       "kk"),
        ("sársauki",     "pain",              "kk"),
        ("þjáning",      "suffering",         "kvk"),
        ("happ",         "luck",              "hk"),
        ("leiðsla",      "guidance",          "kvk"),
        ("vilyrði",      "promise",           "hk"),
        ("frestun",      "postponement",      "kvk"),
        ("samband",      "relationship",      "hk"),
        ("hlynning",     "approval",          "kvk"),
        ("gagnkvæmni",   "reciprocity",       "kvk"),
        ("samþykki",     "approval / consent","hk"),
        ("staðfesting",  "confirmation",      "kvk"),
        ("viðurkenning", "recognition",       "kvk"),
        ("umbun",        "reward",            "kvk"),
        ("refsing",      "punishment",        "kvk"),
        ("dómur",        "judgment / verdict","kk"),
        ("málaferli",    "legal proceedings", "hk"),
        ("kæra",         "complaint",         "kvk"),
        ("kvörtun",      "complaint",         "kvk"),
        ("ábending",     "tip / suggestion",  "kvk"),
        ("gagnrýni",     "criticism",         "kvk"),
        ("umsögn",       "review / comment",  "kvk"),
        ("mat",          "assessment",        "hk"),
        ("könnun",       "survey / study",    "kvk"),
        ("rannsókn",     "investigation",     "kvk"),
        ("niðurgreiðsla","subsidy",           "kvk"),
        ("hlutdeild",    "participation / share","kvk"),
        ("þáttur",       "episode / factor",  "kk"),
        ("verkefni",     "project / task",    "hk"),
        ("áætlun",       "plan / schedule",   "kvk"),
        ("samningur",    "agreement / contract","kk"),
        ("greiðsla",     "payment",           "kvk"),
        ("skattur",      "tax",               "kk"),
        ("verð",         "price",             "hk"),
        ("þóknun",       "fee / compensation","kvk"),
        ("laun",         "salary / wages",    "hk"),
        ("tekjur",       "income / revenue",  "kvk"),
        ("útgjöld",      "expenses",          "hk"),
        ("hagnaður",     "profit",            "kk"),
        ("tap",          "loss",              "hk"),
        ("fjárfesting",  "investment",        "kvk"),
        ("lán",          "loan",              "hk"),
        ("skuld",        "debt",              "kvk"),
        ("hlutabréf",    "share / stock",     "hk"),
        ("gjaldmiðill",  "currency",          "kk"),
        ("kreditkort",   "credit card",       "hk"),
        ("reikningur",   "account / invoice", "kk"),
        ("trygging",     "insurance",         "kvk"),
    ],

    "Hlutir": [
        # ── More household ──
        ("baðkar",       "bathtub",           "kk"),
        ("bakki",        "tray",              "kk"),
        ("bretti",       "board / plank",     "hk"),
        ("fata",         "bucket / pail",     "kvk"),
        ("geymsla",      "storage / pantry",  "kvk"),
        ("karfa",        "basket",            "kvk"),
        ("kerti",        "candle",            "hk"),
        ("krukka",       "jar / jug",         "kvk"),
        ("motta",        "mat / rug",         "kvk"),
        ("pottur",       "pot",               "kk"),
        ("prjón",        "knitting needle",   "kk"),
        ("spegill",      "mirror",            "kk"),
        ("stöng",        "pole / rod",        "kvk"),
        ("súla",         "column / pillar",   "kvk"),
        ("vasi",         "pocket",            "kk"),
        ("vagn",         "wagon / cart",      "kk"),
        ("þráður",       "thread / string",   "kk"),
        ("lyftari",      "elevator / lift",   "kk"),
        ("brunn",        "well",              "kk"),
        ("kross",        "cross",             "kk"),
        ("tjald",        "tent",              "hk"),
        ("spil",         "card game / play",  "hk"),
        ("kafli",        "chapter / section", "kk"),
        ("rúða",         "pane / windowpane", "kvk"),
        ("fat",          "vessel / container","hk"),
        # ── More tools / equipment ──
        ("klippa",       "scissors",          "kvk"),
        ("kefli",        "rolling pin",       "hk"),
        ("þvottaefni",   "detergent",         "hk"),
        ("heita pönna",  "hot pan",           "kvk"),
        ("ketill",       "kettle / cauldron", "kk"),
        ("flaska",       "bottle",            "kvk"),
        ("dós",          "tin / can",         "kvk"),
        ("ílát",         "container",         "hk"),
        ("nál",          "needle",            "kvk"),
        ("reipur",       "rope",              "kk"),
        ("band",         "ribbon / cord",     "hk"),
        ("lás",          "lock / padlock",    "kk"),
        ("stig",         "point / score",     "hk"),
        ("sporðgeirinn", "sharp edge",        "kk"),
        ("silfurpappír", "aluminium foil",    "kk"),
        ("plastic",      "plastic wrap",      "hk"),
        ("heimilistæki", "household appliance","hk"),
        ("brjálæðistæki","broken device",     "hk"),
        ("stýrisbylta",  "control panel",     "kvk"),
        # ── Office / school ──
        ("dagbók",       "diary / journal",   "kvk"),
        ("skrá",         "file / record",     "kvk"),
        ("tafla",        "table / board",     "kvk"),
        ("gluggi",       "window (app)",      "kk"),
        ("uppkast",      "draft",             "hk"),
        ("grein",        "article / branch",  "kvk"),
        ("kort",         "map / card",        "hk"),
        ("veggspjald",   "poster",            "hk"),
        ("merki",        "sign / badge",      "hk"),
        ("stimpill",     "stamp",             "kk"),
        ("umslag",       "envelope",          "hk"),
        ("póstkort",     "postcard",          "hk"),
        ("reikningur",   "bill / invoice",    "kk"),
        ("kvittun",      "receipt",           "kvk"),
        ("skrá",         "file",              "kvk"),
        ("disklingur",   "floppy disk",       "kk"),
        # ── Transport additions ──
        ("vinnuvél",     "construction machine","kvk"),
        ("dráttarvél",   "tractor",           "kvk"),
        ("gangstétt",    "pavement / sidewalk","kvk"),
        ("hlið",         "gate / side",       "kvk"),
        ("girðing",      "fence",             "kvk"),
        ("troðningur",   "pedestrian",        "kk"),
        ("tröppur",      "stairs",            "kvk"),
        # ── Electronics / tech additions ──
        ("loftnet",      "antenna",           "hk"),
        ("tengi",        "connector / port",  "hk"),
        ("snúra",        "cable / cord",      "kvk"),
        ("takki",        "button / key",      "kk"),
        ("rofi",         "switch",            "kk"),
        ("geymir",       "hard drive / tank", "kk"),
        ("gluggabrík",   "window glass pane", "kvk"),
        ("flugdiskur",   "frisbee",           "kk"),
        ("leikjakúla",   "toy ball",          "kvk"),
        ("byssur",       "rifle / gun",       "kvk"),
        ("veiðistöng",   "fishing rod",       "kvk"),
        ("hárlykja",     "hair clip",         "kvk"),
        ("bursti",       "brush",             "kk"),
        ("kampur",       "comb",              "kk"),
        ("sápa",         "soap",              "kvk"),
        ("handklæði",    "towel",             "hk"),
        ("svampur",      "sponge",            "kk"),
        ("spegill",      "mirror",            "kk"),
        # ── Miscellaneous ──
        ("strekk",       "strap / band",      "kk"),
        ("skúff",        "drawer",            "kvk"),
        ("kista",        "chest / box",       "kvk"),
        ("tösku",        "bag",               "kvk"),
        ("hamar",        "hammer",            "kk"),
        ("skrúfjárn",    "screwdriver",       "hk"),
        ("sög",          "saw",               "kvk"),
        ("bolta",        "bolt",              "kk"),
        ("skrúfa",       "screw",             "kvk"),
        ("nagli",        "nail",              "kk"),
        ("stigi",        "ladder",            "kk"),
        ("skúffa",       "shovel / scoop",    "kvk"),
        ("haglér",       "drill bit",         "kk"),
        ("penni",        "pen",               "kk"),
        ("blýantur",     "pencil",            "kk"),
        ("strokleður",   "eraser",            "hk"),
        ("lím",          "glue",              "hk"),
        ("krít",         "chalk",             "kvk"),
        ("pensill",      "brush / paintbrush","kk"),
        ("teiknibord",   "drawing board",     "hk"),
        ("dagbók",       "journal",           "kvk"),
        ("ljósmynd",     "photograph",        "kvk"),
        ("kassi",        "box / crate",       "kk"),
        ("pakki",        "package / parcel",  "kk"),
        ("poki",         "bag / pouch",       "kk"),
        ("net",          "net",               "hk"),
        ("segl",         "sail",              "hk"),
        ("bátslykill",   "boat key",          "kk"),
        ("ankeri",       "anchor",            "hk"),
        ("viti",         "lighthouse",        "kk"),
        ("merkiboð",     "signal",            "hk"),
        ("byssufæri",    "gun cartridge",     "hk"),
        ("vírbúnaður",   "wiring",            "kk"),
        ("efni",         "material",          "hk"),
        ("dúkur",        "cloth",             "kk"),
        ("silki",        "silk",              "hk"),
        ("leður",        "leather",           "hk"),
        ("plast",        "plastic",           "hk"),
        ("ál",           "aluminium",         "hk"),
        ("stál",         "steel",             "hk"),
        ("gúmmí",        "rubber",            "hk"),
        ("asfalt",       "asphalt",           "hk"),
        ("trjávið",      "wood",              "hk"),
        ("glær",         "glass (material)",  "kk"),
        ("marmari",      "marble",            "kk"),
        ("grjót",        "gravel / stones",   "hk"),
    ],

    "Sagnir": [
        # Simple single-word verbs only
        ("ákveða",       "to decide",         "so"),
        ("bíða",         "to wait",           "so"),
        ("biðja",        "to pray / ask",     "so"),
        ("birta",        "to publish / reveal","so"),
        ("blanda",       "to mix / blend",    "so"),
        ("borðа",        "to eat",            "so"),
        ("bæta",         "to improve / add",  "so"),
        ("deyja",        "to die",            "so"),
        ("drepa",        "to kill",           "so"),
        ("dansa",        "to dance",          "so"),
        ("elda",         "to cook",           "so"),
        ("elska",        "to love",           "so"),
        ("fagna",        "to rejoice",        "so"),
        ("fara",         "to go",             "so"),
        ("finna",        "to find",           "so"),
        ("flytja",       "to move / transport","so"),
        ("ganga",        "to walk",           "so"),
        ("gera",         "to do / make",      "so"),
        ("geyma",        "to store / keep",   "so"),
        ("glata",        "to lose",           "so"),
        ("gráta",        "to cry / weep",     "so"),
        ("greiða",       "to pay / comb",     "so"),
        ("hafa",         "to have",           "so"),
        ("hafa",         "to have",           "so"),
        ("hlaupa",       "to run",            "so"),
        ("hlæja",        "to laugh",          "so"),
        ("horfa",        "to watch",          "so"),
        ("hraða",        "to speed up",       "so"),
        ("hreyfa",       "to move",           "so"),
        ("hugsa",        "to think",          "so"),
        ("hvetja",       "to encourage",      "so"),
        ("hyggja",       "to intend / think", "so"),
        ("hjálpa",       "to help",           "so"),
        ("kasta",        "to throw",          "so"),
        ("kaupa",        "to buy",            "so"),
        ("kenna",        "to teach / feel",   "so"),
        ("keyra",        "to drive",          "so"),
        ("klifra",       "to climb",          "so"),
        ("koma",         "to come",           "so"),
        ("kveikja",      "to light / ignite", "so"),
        ("kvarta",       "to complain",       "so"),
        ("laga",         "to fix / repair",   "so"),
        ("landa",        "to land",           "so"),
        ("leika",        "to play",           "so"),
        ("leita",        "to search",         "so"),
        ("lesa",         "to read",           "so"),
        ("lifa",         "to live",           "so"),
        ("líða",         "to pass / feel",    "so"),
        ("ljúka",        "to finish",         "so"),
        ("loka",         "to close",          "so"),
        ("losna",        "to come loose",     "so"),
        ("lyfta",        "to lift",           "so"),
        ("læra",         "to learn",          "so"),
        ("mæla",         "to measure",        "so"),
        ("mæta",         "to meet / attend",  "so"),
        ("mynda",        "to form",           "so"),
        ("nálgast",      "to approach",       "so"),
        ("njóta",        "to enjoy",          "so"),
        ("nota",         "to use",            "so"),
        ("opna",         "to open",           "so"),
        ("panta",        "to order",          "so"),
        ("prófa",        "to try / test",     "so"),
        ("raða",         "to arrange / sort", "so"),
        ("reikna",       "to calculate",      "so"),
        ("reka",         "to run / push",     "so"),
        ("ræða",         "to discuss",        "so"),
        ("safna",        "to collect",        "so"),
        ("samþykkja",    "to approve",        "so"),
        ("selja",        "to sell",           "so"),
        ("sigra",        "to win",            "so"),
        ("sitja",        "to sit",            "so"),
        ("sjá",          "to see",            "so"),
        ("skilja",       "to understand",     "so"),
        ("slá",          "to hit",            "so"),
        ("slökkva",      "to turn off",       "so"),
        ("snúa",         "to turn",           "so"),
        ("sofa",         "to sleep",          "so"),
        ("sofna",        "to fall asleep",    "so"),
        ("spyrja",       "to ask",            "so"),
        ("spila",        "to play (music)",   "so"),
        ("sýna",         "to show",           "so"),
        ("sækja",        "to fetch",          "so"),
        ("syngja",       "to sing",           "so"),
        ("taka",         "to take",           "so"),
        ("tala",         "to speak",          "so"),
        ("telja",        "to count",          "so"),
        ("þakka",        "to thank",          "so"),
        ("þola",         "to tolerate",       "so"),
        ("þreyja",       "to long for",       "so"),
        ("vakna",        "to wake up",        "so"),
        ("vaxa",         "to grow",           "so"),
        ("vega",         "to weigh",          "so"),
        ("velja",        "to choose",         "so"),
        ("verða",        "to become",         "so"),
        ("virkja",       "to activate",       "so"),
        ("vista",        "to save / host",    "so"),
        ("vofa",         "to loom / hover",   "so"),
        ("bræða",        "to melt",           "so"),
        ("byltast",      "to roll",           "so"),
        ("deyfa",        "to dull / numb",    "so"),
        ("dreifa",       "to spread / distribute","so"),
        ("fegra",        "to beautify",       "so"),
        ("freista",      "to tempt / try",    "so"),
        ("glæpa",        "to commit a crime", "so"),
        ("gróa",         "to heal / grow",    "so"),
        ("hafa",         "to contain",        "so"),
        ("hlusta",       "to listen",         "so"),
        ("hniga",        "to sink / decline", "so"),
        ("leiðbeina",    "to guide",          "so"),
        ("leyna",        "to hide",           "so"),
        ("ljósmynda",    "to photograph",     "so"),
        ("loka",         "to block / close",  "so"),
        ("meta",         "to assess",         "so"),
        ("minna",        "to remind",         "so"),
        ("nema",         "to study",          "so"),
        ("sameina",      "to unite",          "so"),
        ("skipta",       "to divide / exchange","so"),
        ("skoða",        "to look at",        "so"),
        ("smakka",       "to taste",          "so"),
        ("standa",       "to stand",          "so"),
        ("styðja",       "to support",        "so"),
        ("sýna",         "to demonstrate",    "so"),
        ("þjálfa",       "to train",          "so"),
        ("umbreyta",     "to transform",      "so"),
        ("veita",        "to grant / provide","so"),
        ("þróa",         "to develop",        "so"),
        ("afrita",       "to copy",           "so"),
        ("klára",        "to finish / complete","so"),
        ("setja",        "to place / set",    "so"),
        ("skipta",       "to exchange",       "so"),
        ("stoppa",       "to stop",           "so"),
        ("styðja",       "to support",        "so"),
        ("sækja",        "to collect",        "so"),
        ("bjóða",        "to offer / invite", "so"),
        ("bera",         "to bear / carry",   "so"),
        ("breyta",       "to change",         "so"),
        ("byrja",        "to begin",          "so"),
        ("deila",        "to share / argue",  "so"),
        ("eiga",         "to own",            "so"),
        ("fá",           "to get",            "so"),
        ("finna",        "to feel",           "so"),
        ("flýta",        "to hurry",          "so"),
        ("gefa",         "to give",           "so"),
        ("hafa",         "to have",           "so"),
        ("halda",        "to hold",           "so"),
        ("heimsækja",    "to visit",          "so"),
        ("heitа",        "to be called",      "so"),
        ("hitta",        "to meet",           "so"),
        ("hlaupa",       "to escape",         "so"),
        ("horfa",        "to look",           "so"),
        ("hreinsa",      "to clean",          "so"),
        ("hugsa",        "to ponder",         "so"),
        ("kenna",        "to recognize",      "so"),
        ("leyfa",        "to allow",          "so"),
        ("líta",         "to look",           "so"),
        ("míga",         "to urinate",        "so"),
        ("mynda",        "to photograph",     "so"),
        ("ná",           "to reach",          "so"),
        ("nálgast",      "to near",           "so"),
        ("ráða",         "to advise",         "so"),
        ("reyna",        "to try",            "so"),
        ("rísa",         "to rise",           "so"),
        ("ræða",         "to talk about",     "so"),
        ("safna",        "to gather",         "so"),
        ("selja",        "to trade",          "so"),
        ("sendа",        "to send",           "so"),
        ("sitja",        "to stay",           "so"),
        ("skilja",       "to separate",       "so"),
        ("sópa",         "to sweep",          "so"),
        ("svara",        "to reply",          "so"),
        ("þiggja",       "to accept",         "so"),
        ("þrífa",        "to tidy",           "so"),
        ("þvo",          "to wash",           "so"),
        ("umbreyta",     "to convert",        "so"),
        ("umbreyta",     "to change",         "so"),
        ("veðja",        "to bet",            "so"),
        ("vernda",       "to protect",        "so"),
    ],

    "Náttúra": [
        # ── More landscape / geography ──
        ("hnjúkur",      "peak / summit",     "kk"),
        ("hlíð",         "hillside / slope",  "kvk"),
        ("mýri",         "marsh / bog",       "kvk"),
        ("nes",          "headland / cape",   "hk"),
        ("hreysi",       "stone mound",       "hk"),
        ("melar",        "stony plain",       "kk"),
        ("engill",       "meadow / angel",    "kk"),
        ("rústir",       "ruins",             "kvk"),
        ("gígur",        "crater",            "kk"),
        ("hraun",        "lava field",        "hk"),
        ("slétta",       "plain / flatland",  "kvk"),
        ("eyri",         "sandbar / spit",    "kvk"),
        ("fjörður",      "fjord",             "kk"),
        ("dalur",        "valley",            "kk"),
        ("gjá",          "ravine / rift",     "kvk"),
        # ── More sky / weather ──
        ("veðrið",       "the weather",       "hk"),
        ("loftslag",     "climate",           "hk"),
        ("hitabylgja",   "heat wave",         "kvk"),
        ("frostmark",    "freezing point",    "hk"),
        ("regnbogi",     "rainbow",           "kk"),
        ("hárléttir",    "light snow",        "kk"),
        ("slydda",       "sleet",             "kvk"),
        ("frostrigning", "freezing rain",     "kvk"),
        ("brim",         "surf / breakers",   "hk"),
        ("alda",         "wave / swell",      "kvk"),
        # ── More water ──
        ("laug",         "hot spring",        "kvk"),
        ("lón",          "lagoon",            "hk"),
        ("brunni",       "well / spring",     "kk"),
        ("lækur",        "stream / brook",    "kk"),
        ("kvos",         "bay / creek",       "kvk"),
        ("sund",         "sound / strait",    "hk"),
        ("sjórinn",      "the ocean",         "kk"),
        # ── More flora ──
        ("þistill",      "thistle",           "kk"),
        ("lyng",         "heather",           "hk"),
        ("birkitré",     "birch tree",        "hk"),
        ("fura",         "pine tree",         "kvk"),
        ("grenitré",     "spruce tree",       "hk"),
        ("þara",         "seaweed",           "kk"),
        ("mosi",         "moss",              "kk"),
        ("sveppur",      "mushroom",          "kk"),
        ("seyðir",       "rush / reed",       "kk"),
        ("blóm",         "flower",            "hk"),
        ("rosin",        "rose",              "kvk"),
        ("laufskógar",   "deciduous forest",  "kk"),
        ("víðir",        "willow",            "kk"),
        # ── More elements ──
        ("kol",          "coal",              "hk"),
        ("olía",         "oil",               "kvk"),
        ("gas",          "gas",               "hk"),
        ("rafmagn",      "electricity",       "hk"),
        ("geislar",      "rays / radiation",  "kk"),
        ("þyngdarafl",   "gravity",           "hk"),
        ("segulmagn",    "magnetism",         "hk"),
        ("efni",         "substance",         "hk"),
        ("lífrænt",      "organic",           "hk"),
        ("lofttegundir", "gases (pl.)",       "kvk"),
        # ── More ecosystems ──
        ("skógar",       "forests",           "kk"),
        ("slóð",         "trail / track",     "kvk"),
        ("náttúruvernd", "nature conservation","kvk"),
        ("lífríki",      "ecosystem",         "hk"),
        ("lífræður",     "organism",          "kk"),
        ("planta",       "plant",             "kvk"),
        ("þörungur",     "algae",             "kk"),
        ("jarðvegur",    "soil",              "kk"),
        ("sandur",       "sand",              "kk"),
        ("leir",         "clay",              "kk"),
        ("mold",         "soil / earth",      "kvk"),
        ("grjót",        "rock / stones",     "hk"),
        ("kalk",         "lime / calcium",    "hk"),
        ("saltur",       "salt (natural)",    "kk"),
        ("brennisteinssýra","sulfuric acid",  "kvk"),
    ],

    "Líkami": [
        # ── More body parts ──
        ("liðamót",      "joint (anatomy)",   "hk"),
        ("axir",         "shoulders",         "kvk"),
        ("axlarblaðan",  "shoulder blade",    "kvk"),
        ("bringa",       "sternum / chest",   "kvk"),
        ("rifbein",      "rib",               "hk"),
        ("mjóbaksvöðvar","lower back muscles","kk"),
        ("kviður",       "abdomen",           "kk"),
        ("nöf",          "navel / belly button","kvk"),
        ("kynfæri",      "genitals",          "hk"),
        ("lundur",       "groin",             "kk"),
        ("legur",        "hip",               "kk"),
        ("rassinn",      "buttock",           "kk"),
        ("hnékútur",     "kneecap",           "kk"),
        ("önkli",        "ankle",             "kk"),
        ("tánaill",      "toenail",           "kk"),
        ("takmark",      "temple (head)",     "hk"),
        ("kinnar",       "cheeks",            "kvk"),
        ("kjálki",       "jaw",               "kk"),
        ("góm",          "palate / gum",      "kk"),
        ("manngíll",     "larynx / throat",   "kk"),
        ("lungu",        "lung (informal)",   "hk"),
        ("lifur",        "liver",             "kvk"),
        ("nýra",         "kidney",            "hk"),
        ("brisi",        "pancreas",          "kk"),
        ("þarmur",       "intestine",         "kk"),
        ("ristill",      "colon",             "kk"),
        ("blöðruhálsn",  "prostate",          "kk"),
        ("eggjastokkar", "ovary",             "kk"),
        ("legs",         "uterus",            "kk"),
        ("æðar",         "veins",             "kvk"),
        ("slagæð",       "artery",            "kvk"),
        ("mein",         "disease / ailment", "hk"),
        ("bólga",        "inflammation",      "kvk"),
        ("sár",          "wound",             "hk"),
        ("meiðsli",      "injury",            "hk"),
        ("bylta",        "fracture",          "kvk"),
        ("slæðingur",    "bruise",            "kk"),
        ("brenna",       "burn",              "kvk"),
        ("grafargangur", "decay",             "kk"),
        ("geislavirkni", "radiation",         "kvk"),
        ("þunglyndi",    "depression",        "hk"),
        ("kvíðinn",      "anxiety",           "kk"),
        ("insómnia",     "insomnia",          "kvk"),
        ("sykursýki",    "diabetes",          "kvk"),
        ("blóðþrýstingur","blood pressure",   "kk"),
        ("hjartaöng",    "angina",            "kvk"),
        ("lyfjagjöf",    "drug administration","kvk"),
        ("skurðaðgerð",  "surgery",           "kvk"),
        ("röntgengeislar","x-rays",           "kk"),
        ("blóðrannsókn", "blood test",        "kvk"),
    ],

    "Klæði": [
        # ── More clothing ──
        ("sokkar",       "socks (pl.)",       "kk"),
        ("handskfatnaður","glove clothing",   "kk"),
        ("höfuðfatnaður","headgear",          "kk"),
        ("skónagli",     "shoe nail",         "kk"),
        ("skóhvelfing",  "shoe arch",         "kvk"),
        ("skóband",      "shoelace",          "hk"),
        ("höfuðdúkur",   "headscarf",         "kk"),
        ("brimhöfuðfat", "bathing cap",       "hk"),
        ("þvottaefni",   "detergent",         "hk"),
        ("fatnaður",     "clothing",          "kk"),
        ("klæðnaður",    "garments",          "kk"),
        ("dúkur",        "cloth / fabric",    "kk"),
        ("ull",          "wool",              "kvk"),
        ("bómull",       "cotton",            "kvk"),
        ("nylon",        "nylon",             "hk"),
        ("flís",         "fleece",            "kvk"),
        ("veröld",       "old garment",       "kvk"),
        ("galvagall",    "old jumper",        "kk"),
        ("skinn",        "skin / leather",    "hk"),
        ("búningur",     "costume / suit",    "kk"),
        ("jakki",        "jacket",            "kk"),
        ("skikkja",      "cloak / cape",      "kvk"),
        ("sloppur",      "dressing gown",     "kk"),
        ("næturfatnaður","nightwear",         "kk"),
        ("píjama",       "pyjamas",           "kvk"),
        ("næturbuxur",   "pyjama bottoms",    "kvk"),
        ("sokkabuxur",   "tights / stockings","kvk"),
        ("háls­kragi",   "turtleneck",        "kk"),
        ("regnkápa",     "raincoat",          "kvk"),
        ("regnjakki",    "rain jacket",       "kk"),
        ("þykkt jakki",  "heavy jacket",      "kk"),
        ("leikfimitreyja","gymnastics jersey","kvk"),
        ("sundbolur",    "swimsuit / swim top","kk"),
        ("sundskýla",    "swimming trunks",   "kvk"),
        ("íþróttaskór",  "sports shoes",      "kk"),
        ("jógabuxur",    "yoga pants",        "kvk"),
        ("hjólreiðakápa","cycling jacket",    "kvk"),
        ("hlífðarbúningur","protective gear", "kk"),
        ("verndarjakki", "protective jacket", "kk"),
        ("öryggishanska","safety glove",      "kk"),
    ],

    "Dýr": [
        # ── More Icelandic animals / corrections ──
        ("rjúpa",        "ptarmigan",         "kvk"),
        ("blæja",        "bat",               "kvk"),
        ("reyðarmagi",   "red squirrel",      "kk"),
        ("marfluer",     "sandhoppers",       "kvk"),
        ("fargall",      "rook (bird)",       "kk"),
        ("gull",         "goldfinch",         "kk"),
        ("skjaldburkni", "woodlouse",         "kk"),
        ("fura",         "weasel",            "kvk"),
        ("hermelin",     "stoat / ermine",    "kk"),
        ("snata",        "snipe (bird)",      "kvk"),
        ("músarrindill", "wren",              "kk"),
        ("rjúpuseggur",  "ptarmigan egg",     "kk"),
        # ── More sea life ──
        ("tinnskarfur",  "shag (bird)",       "kk"),
        ("hringur",      "ring (anatomy)",    "kk"),
        ("þorskskegg",   "cod beard",         "hk"),
        ("sjóstjarnan",  "starfish",          "kvk"),
        ("sjóstjarna",   "starfish",          "kvk"),
        ("krabbadýr",    "crustacean",        "hk"),
        ("skeldýr",      "shellfish",         "hk"),
        ("lindýr",       "mollusc",           "hk"),
        ("þýfingur",     "lamprey",           "kk"),
        ("tóarfi",       "shrimp (small)",    "kk"),
        # ── More common wild ──
        ("eri",          "eagle owl",         "kk"),
        ("grákráka",     "hooded crow",       "kvk"),
        ("stari",        "starling",          "kk"),
        ("þúfutittlingur","meadow pipit",     "kk"),
        ("snjótittlingur","snow bunting",     "kk"),
        ("tjaldur",      "oystercatcher",     "kk"),
        ("lóa",          "golden plover",     "kvk"),
        ("heiðlóa",      "golden plover",     "kvk"),
        ("þvari",        "dunlin",            "kk"),
        ("sendlingur",   "purple sandpiper",  "kk"),
        ("sporðgeli",    "golden eagle",      "kk"),
        ("hrafnsungi",   "young raven",       "kk"),
        ("óðinshani",    "red-necked phalarope","kk"),
        ("rauðbryst",    "robin (bird)",      "hk"),
    ],

    "Nýyrði": [
        # ── More technology ──
        ("smáforriti",   "microservice",      "hk"),
        ("keyrsluumhverfi","runtime environment","hk"),
        ("vefur",        "web",               "kk"),
        ("gagnasöfnun",  "data collection",   "kvk"),
        ("skýjaþjónusta","cloud service",     "kvk"),
        ("þjónustulag",  "service layer",     "hk"),
        ("grein",        "branch (code)",     "kvk"),
        ("villukóði",    "error code",        "kk"),
        ("villupóstur",  "error mail",        "kk"),
        ("smásjá",       "microscope",        "kvk"),
        ("sjónauki",     "telescope",         "kk"),
        ("röntgenljós",  "X-ray light",       "hk"),
        ("hitamæll",     "thermometer",       "kk"),
        ("þrýstimæll",   "pressure gauge",    "kk"),
        ("raftaugaboð",  "neural network",    "hk"),
        ("gangur",       "corridor",          "kk"),
        ("víðsjá",       "wide-angle (lens)", "kvk"),
        ("rafknúinn",    "electric powered",  "kk"),
        ("sólarafli",    "solar power",       "kk"),
        ("kynlíf",       "sex / sexual life", "hk"),
        ("jafngildi",    "equivalent",        "hk"),
        ("sameiginlegur","shared / common",   "kk"),
        ("vísitala",     "index",             "kvk"),
        ("staðfest",     "confirmed",         "hk"),
        ("tilkynning",   "notification",      "kvk"),
        ("skeyti",       "message / telegram","hk"),
        ("netfang",      "email address",     "hk"),
        ("lykilorð",     "password",          "hk"),
        ("notandi",      "user",              "kk"),
        ("gagnasafn",    "database",          "hk"),
        ("gervigreind",  "artificial intelligence","kvk"),
        ("reiknirit",    "algorithm",         "hk"),
        ("uppfærsla",    "update",            "kvk"),
        ("niðurhal",     "download",          "hk"),
        ("hleðsla",      "charging / loading","kvk"),
        ("rafhlöðu",     "battery",           "kvk"),
        ("samfélagsmiðlar","social media",    "kk"),
        ("áhrifamaður",  "influencer",        "kk"),
        ("áskrift",      "subscription",      "kvk"),
        ("auglýsing",    "advertisement",     "kvk"),
        ("innihald",     "content",           "hk"),
        ("smárit",       "blog",              "hk"),
        ("kvikmyndavefur","streaming service","kk"),
    ],

    "Matur": [
        # ── More food ──
        ("smjör",        "butter",            "hk"),
        ("lard",         "lard",              "hk"),
        ("hneta",        "nut",               "kvk"),
        ("möndlur",      "almond",            "kvk"),
        ("heslihneta",   "hazelnut",          "kvk"),
        ("maísflögur",   "cornflakes",        "kvk"),
        ("hafrar",       "oats",              "kk"),
        ("kókosmjólk",   "coconut milk",      "kvk"),
        ("sojamjólk",    "soy milk",          "kvk"),
        ("haframjólk",   "oat milk",          "kvk"),
        ("hveitibrauð",  "white bread",       "hk"),
        ("kringlur",     "ring-shaped pastry","kvk"),
        ("kleinur",      "twisted doughnut",  "kvk"),
        ("laufabrauð",   "leaf bread (Xmas)", "hk"),
        ("hangikjöt",    "smoked lamb",       "hk"),
        ("skál",         "bowl",              "kvk"),
        ("dót",          "stuff (food)",      "hk"),
        ("sætar",        "sweets",            "kvk"),
        ("sulta",        "jam / preserve",    "kvk"),
        ("dýrindis",     "treat / tidbit",    "hk"),
        ("lakkrís",      "liquorice",         "hk"),
        ("nammi",        "sweets / candy",    "hk"),
        ("þurrkað ávöxtur","dried fruit",     "kk"),
        ("þurrkaður",    "dried (food)",      "kk"),
        ("kóngulóarsúpa","pumpkin soup",      "kvk"),
        ("rjómaostur",   "cream cheese",      "kk"),
        ("brieostur",    "brie cheese",       "kk"),
        ("blámyglostur", "blue cheese",       "kk"),
        ("fetaostur",    "feta cheese",       "kk"),
        ("gouda",        "gouda cheese",      "hk"),
        ("parmesan",     "parmesan cheese",   "hk"),
        ("ricotta",      "ricotta",           "hk"),
        ("srimp",        "shrimp",            "hk"),
        ("tindabikkja",  "dogfish",           "kvk"),
        ("þorskur",      "cod",               "kk"),
        ("roe",          "fish roe",          "hk"),
        ("kavíar",       "caviar",            "hk"),
        ("humarmjöl",    "lobster bisque",    "hk"),
        ("sætur kartöflur","sweet potato",    "kvk"),
        ("baunaspírar",  "bean sprouts",      "kk"),
        ("blaðlaukur",   "leek",              "kk"),
        ("blaðsalat",    "romaine lettuce",   "hk"),
        ("rauðkál",      "red cabbage",       "hk"),
        ("hvítkál",      "white cabbage",     "hk"),
        ("grænmeti",     "vegetables",        "hk"),
        ("ávöxtur",      "fruit",             "kk"),
        ("rótargrænmeti","root vegetables",   "hk"),
        ("spergilkál",   "asparagus",         "hk"),
        ("artishokkur",  "artichoke",         "kk"),
        ("engifer",      "ginger",            "kk"),
        ("saffran",      "saffron",           "hk"),
        ("lárviðarlauf", "bay leaf",          "hk"),
        ("þangsulta",    "seaweed jam",       "kvk"),
        ("skrúðsafi",    "elderflower cordial","kk"),
    ],
}
