"""
Third wave — very conservative picks for maximum BÍN hit rate.
"""

EXTRA3 = {
    "Nöfn": [
        ("andi",         "spirit / breath",   "kk"),
        ("eigandi",      "owner",             "kk"),
        ("ferð",         "journey / trip",    "kvk"),
        ("fyrirlæstur",  "lecture",           "kk"),
        ("gangur",       "corridor / gait",   "kk"),
        ("heiður",       "honour / glory",    "kk"),
        ("kapp",         "zeal / effort",     "hk"),
        ("leit",         "search",            "kvk"),
        ("lið",          "team / joint",      "hk"),
        ("líkan",        "model",             "hk"),
        ("massi",        "mass",              "kk"),
        ("minni",        "memory / toast",    "hk"),
        ("ráð",          "advice / means",    "hk"),
        ("sinn",         "time / occasion",   "hk"),
        ("sjón",         "sight / vision",    "kvk"),
        ("skylda",       "duty / obligation", "kvk"),
        ("skor",         "score / notch",     "hk"),
        ("snúningur",    "rotation / turn",   "kk"),
        ("taug",         "string / wire",     "kvk"),
        ("uppgötvun",    "discovery",         "kvk"),
        ("útlit",        "appearance",        "hk"),
        ("vinningur",    "win / profit",      "kk"),
        ("þakklæti",     "gratitude",         "hk"),
        ("þraut",        "ordeal / puzzle",   "kvk"),
        ("öxl",          "shoulder",          "kvk"),
        ("rót",          "root",              "kvk"),
        ("þögn",         "silence",           "kvk"),
        ("þing",         "parliament",        "hk"),
        ("vera",         "being / existence", "kvk"),
        ("hlynning",     "support",           "kvk"),
        ("hné",          "knee",              "hk"),
        ("bak",          "back (body)",       "hk"),
        ("hálsmál",      "neck size",         "hk"),
        ("spyrna",       "resistance / kick", "kvk"),
        ("öfl",          "strength (pl.)",    "hk"),
        ("þolinmæði",    "patience",          "kvk"),
        ("kunnátta",     "knowledge / skill", "kvk"),
        ("þekking",      "knowledge",         "kvk"),
        ("reynsla",      "experience",        "kvk"),
        ("heilbrigði",   "health",            "hk"),
        ("hugrekki",     "courage",           "hk"),
        ("áræðni",       "boldness",          "kvk"),
        ("þrá",          "longing",           "kvk"),
        ("þrór",         "longing (alt.)",    "kk"),
        ("villandi",     "misleading",        "kk"),
        ("lykill",       "key",               "kk"),
        ("skil",         "comprehension",     "hk"),
        ("þreki",        "toughness",         "kk"),
        ("bending",      "signal / gesture",  "kvk"),
        ("þolinmæðin",   "the patience",      "kvk"),
    ],

    "Hlutir": [
        ("farartæki",    "vehicle",           "hk"),
        ("hjálpar­búnaður","auxiliary gear",  "kk"),
        ("gryfja",       "pit / hole",        "kvk"),
        ("hlíf",         "shield / protection","kvk"),
        ("hvolf",        "vault / dome",      "hk"),
        ("ketill",       "kettle / cauldron", "kk"),
        ("krukka",       "jar",               "kvk"),
        ("ljósker",      "lantern",           "hk"),
        ("mál",          "measure",           "hk"),
        ("matur",        "food",              "kk"),
        ("naglar",       "nails",             "kk"),
        ("nagli",        "nail",              "kk"),
        ("sámur",        "fishing hook",      "kk"),
        ("fisknet",      "fishing net",       "hk"),
        ("gler",         "glass",             "hk"),
        ("hlíð",         "side / flap",       "kvk"),
        ("hrot",         "snout",             "hk"),
        ("hnútur",       "knot / node",       "kk"),
        ("ör",           "arrow",             "kvk"),
        ("spjót",        "spear",             "hk"),
        ("skjöldur",     "shield",            "kk"),
        ("sverð",        "sword",             "hk"),
        ("bogi",         "bow (weapon)",      "kk"),
        ("líkisti",      "coffin",            "kk"),
        ("stigi",        "ladder",            "kk"),
        ("veggur",       "wall",              "kk"),
        ("þakið",        "the ceiling",       "hk"),
        ("gólf",         "floor",             "hk"),
        ("hlið",         "side door",         "kvk"),
        ("dyr",          "door(s)",           "kvk"),
        ("gluggi",       "window",            "kk"),
        ("þvottur",      "wash",              "kk"),
        ("þykkt",        "thickness",         "kvk"),
        ("rafhlaða",     "battery",           "kvk"),
        ("rafall",       "generator",         "kk"),
        ("ljóspera",     "light bulb",        "kvk"),
        ("viðvörun",     "warning",           "kvk"),
        ("prófun",       "testing",           "kvk"),
        ("kynning",      "presentation",      "kvk"),
        ("ritgerð",      "essay",             "kvk"),
        ("kóðaorð",      "codeword",          "hk"),
        ("þema",         "theme",             "hk"),
        ("gerðarheitið", "type name",         "hk"),
    ],

    "Sagnir": [
        ("blása",        "to blow",           "so"),
        ("kalla",        "to call",           "so"),
        ("leiga",        "to rent",           "so"),
        ("meina",        "to mean",           "so"),
        ("refsa",        "to punish",         "so"),
        ("skynja",       "to perceive",       "so"),
        ("smyrja",       "to grease / spread","so"),
        ("spara",        "to spare / save",   "so"),
        ("stara",        "to stare",          "so"),
        ("þora",         "to dare",           "so"),
        ("rúlla",        "to roll",           "so"),
        ("þramma",       "to stomp",          "so"),
        ("kenna",        "to teach",          "so"),
        ("gjöra",        "to do",             "so"),
        ("flýja",        "to flee",           "so"),
        ("hníga",        "to decline / bow",  "so"),
        ("geysa",        "to gush / surge",   "so"),
        ("þenja",        "to extend",         "so"),
        ("hreifa",       "to stir",           "so"),
        ("kveina",       "to moan",           "so"),
        ("þræða",        "to thread",         "so"),
        ("hlífa",        "to protect",        "so"),
        ("hlera",        "to eavesdrop",      "so"),
        ("stíga",        "to step up",        "so"),
        ("hraðlæsa",     "to speed-read",     "so"),
        ("selta",        "to list",           "so"),
        ("þverbreyta",   "to change fundamentally","so"),
        ("binda",        "to bind",           "so"),
        ("hnýta",        "to tie a knot",     "so"),
        ("þagna",        "to grow silent",    "so"),
        ("þykja",        "to seem / feel",    "so"),
        ("ganga",        "to progress",       "so"),
        ("slíta",        "to tear / wear out","so"),
        ("hvesta",       "to tighten",        "so"),
        ("þrjóta",       "to run out",        "so"),
        ("mega",         "may / to be allowed","so"),
        ("skulu",        "shall / must",      "so"),
        ("munu",         "will / shall",      "so"),
        ("geta",         "to manage / be able","so"),
        ("fela",         "to hide / conceal", "so"),
        ("vaða",         "to wade",           "so"),
        ("glíma",        "to wrestle / grapple","so"),
        ("þjóna",        "to serve",          "so"),
        ("elta",         "to chase",          "so"),
        ("hýsa",         "to house / host",   "so"),
        ("klappa",       "to clap",           "so"),
        ("sníkja",       "to cheat / sponge", "so"),
        ("svíkja",       "to betray",         "so"),
        ("kveðja",       "to bid farewell",   "so"),
        ("þjappa",       "to pack / compress","so"),
    ],

    "Náttúra": [
        ("rigning",      "rainfall",          "kvk"),
        ("jökull",       "glacier",           "kk"),
        ("frost",        "frost",             "hk"),
        ("þoka",         "fog",               "kvk"),
        ("dögg",         "dew",               "kvk"),
        ("rok",          "gale / wind",       "hk"),
        ("Hekla",        "Hekla (volcano)",   "kvk"),
        ("Öxará",        "Öxará (river)",     "kvk"),
        ("Þingvellir",   "Þingvellir",        "hk"),
        ("Mývatn",       "Lake Mývatn",       "hk"),
        ("sandmellur",   "sandbank",          "kk"),
        ("hraunklöpp",   "lava rock",         "kvk"),
        ("þverá",        "cross-river",       "kvk"),
        ("heimsskaut",   "pole of the earth", "hk"),
        ("þjóðleið",     "national route",    "kvk"),
        ("þjóðvegur",    "national road",     "kk"),
        ("jarðhiti",     "geothermal heat",   "kk"),
        ("gufa",         "steam / vapour",    "kvk"),
        ("eldur",        "fire",              "kk"),
        ("aska",         "ash",               "kvk"),
        ("kola",         "coal piece",        "kvk"),
        ("gott",         "goodness",          "hk"),
        ("heimi",        "world / home",      "kk"),
        ("líf",          "life (nature)",     "hk"),
        ("framtíð",      "future",            "kvk"),
    ],

    "Líkami": [
        ("axir",         "shoulders",         "kvk"),
        ("öxl",          "shoulder",          "kvk"),
        ("þvers",        "thighbone",         "hk"),
        ("sáð",          "semen / seed",      "hk"),
        ("þungaðar",     "pregnant women",    "kvk"),
        ("þyngd",        "weight",            "kvk"),
        ("hæð",          "height",            "kvk"),
        ("þvermál",      "diameter",          "hk"),
        ("bygging",      "build / physique",  "kvk"),
        ("lögun",        "shape / figure",    "kvk"),
        ("mein",         "ailment",           "hk"),
        ("bólginn",      "swollen (adj.)",    "kk"),
        ("þroti",        "swelling",          "kk"),
        ("krampi",       "cramp",             "kk"),
        ("verkur",       "pain / ache",       "kk"),
        ("höfuðverkur",  "headache",          "kk"),
        ("magaverkur",   "stomach ache",      "kk"),
        ("beinbrot",     "bone fracture",     "hk"),
        ("hálssár",      "sore throat",       "hk"),
        ("kvef",         "cold (illness)",    "hk"),
        ("hiti",         "fever",             "kk"),
        ("mæðin",        "the shortness",     "kvk"),
        ("þreyta",       "fatigue / tiredness","kvk"),
        ("þunglyndi",    "depression",        "hk"),
        ("kvíði",        "anxiety",           "kk"),
    ],

    "Klæði": [
        ("rauður",       "red (colour)",      "kk"),
        ("blár",         "blue (colour)",     "kk"),
        ("grær",         "grey (colour)",     "kk"),
        ("hvítur",       "white (colour)",    "kk"),
        ("svartur",      "black (colour)",    "kk"),
        ("gulur",        "yellow (colour)",   "kk"),
        ("grænn",        "green (colour)",    "kk"),
        ("fjólublár",    "purple (colour)",   "kk"),
        ("appelsínugulur","orange (colour)",  "kk"),
        ("bleikur",      "pink (colour)",     "kk"),
        ("brúnn",        "brown (colour)",    "kk"),
        ("gráblár",      "grey-blue",         "kk"),
        ("skikkja",      "cape / cloak",      "kvk"),
        ("brók",         "underwear",         "kvk"),
        ("hanska",       "glove (alt.)",      "kk"),
        ("stígvél",      "boot",              "hk"),
        ("sandali",      "sandal",            "kk"),
        ("ljósbrúnn",    "light brown",       "kk"),
        ("dökkur",       "dark (colour)",     "kk"),
        ("meðalgömul",   "middle-aged",       "kvk"),
        ("þjóðbúningur", "national costume",  "kk"),
        ("faldbúningur", "traditional Icelandic dress","kk"),
        ("upphlutur",    "bodice / bib",      "kk"),
        ("brjóstakross", "chest cross",       "kk"),
        ("þvottur",      "washing",           "kk"),
    ],

    "Dýr": [
        ("geitungur",    "wasp",              "kk"),
        ("bý",           "bee",               "kvk"),
        ("fiðrildi",     "butterfly",         "hk"),
        ("maðkur",       "worm",              "kk"),
        ("þistilfjaran", "thistle caterpillar","kk"),
        ("lúsa",         "louse",             "kvk"),
        ("lús",          "louse (alt.)",      "kvk"),
        ("fluga",        "fly (insect)",      "kvk"),
        ("sáldur",       "beetle",            "kk"),
        ("skordýr",      "insect",            "hk"),
        ("könguló",      "spider",            "kvk"),
        ("svartfugl",    "black guillemot",   "kk"),
        ("þyrill",       "hummingbird",       "kk"),
        ("kúrekur",      "cowboy / cowpoke",  "kk"),
        ("þyrla",        "helicopter",        "kvk"),
        ("tígur",        "tiger",             "kk"),
        ("ljón",         "lion",              "hk"),
        ("gepard",       "cheetah",           "kk"),
        ("nashyrningur", "rhinoceros",        "kk"),
        ("flóðhestur",   "hippopotamus",      "kk"),
        ("fíll",         "elephant",          "kk"),
        ("refur",        "fox (alt. entry)",  "kk"),
        ("geit",         "goat",              "kvk"),
        ("ær",           "ewe",               "kvk"),
        ("naut",         "bull / ox",         "hk"),
    ],
}
