"""
Second wave of extra entries — simpler words with higher BÍN hit-rate.
No compound lemmas, no middle-voice verbs, no plural-only nouns.
"""

EXTRA2 = {
    "Nöfn": [
        # ── Abstract ──
        ("aldur",        "age",               "kk"),
        ("bekkur",       "bench / class",     "kk"),
        ("draumur",      "dream",             "kk"),
        ("fegurð",       "beauty",            "kvk"),
        ("frændi",       "uncle / male cousin","kk"),
        ("frænka",       "aunt / female cousin","kvk"),
        ("gáfa",         "talent / gift",     "kvk"),
        ("gerð",         "type / kind",       "kvk"),
        ("hópur",        "group",             "kk"),
        ("íbúi",         "resident",          "kk"),
        ("jaðar",        "edge / margin",     "kk"),
        ("kafli",        "chapter",           "kk"),
        ("kostnaður",    "cost / expense",    "kk"),
        ("leikni",       "skill",             "kvk"),
        ("leyfi",        "permission / leave","hk"),
        ("líf",          "life",              "hk"),
        ("menntun",      "education",         "kvk"),
        ("peningur",     "coin / money",      "kk"),
        ("ritgerð",      "essay",             "kvk"),
        ("sál",          "soul",              "kvk"),
        ("skilningur",   "understanding",     "kk"),
        ("stúdent",      "student",           "kk"),
        ("tár",          "tear (drop)",       "hk"),
        ("tjáning",      "expression",        "kvk"),
        ("umræða",       "discussion",        "kvk"),
        ("val",          "choice",            "hk"),
        ("viðbragð",     "reaction / response","hk"),
        ("vinnustaður",  "workplace",         "kk"),
        ("þörf",         "need / necessity",  "kvk"),
        ("þorp",         "village",           "hk"),
        ("öfund",        "envy",              "kvk"),
        ("fræðsla",      "instruction",       "kvk"),
        ("gróska",       "growth / vitality", "kvk"),
        ("hlutlægni",    "objectivity",       "kvk"),
        ("starf",        "job / occupation",  "hk"),
        ("vöxtur",       "growth",            "kk"),
        ("mark",         "mark / goal",       "hk"),
        ("miður",        "middle",            "kk"),
        ("sturkur",      "push / shove",      "kk"),
        ("forsaga",      "background story",  "kvk"),
        ("greinarmunur", "distinction",       "kk"),
        ("boðun",        "invitation",        "kvk"),
        ("þrjóska",      "stubbornness",      "kvk"),
        ("þrekur",       "endurance",         "kk"),
        ("hraðstopp",    "emergency stop",    "kk"),
        ("áskorun",      "challenge",         "kvk"),
        ("framtíð",      "future",            "kvk"),
        ("fortíð",       "past",              "kvk"),
        ("nútími",       "present (time)",    "kk"),
        ("hlutfall",     "ratio / proportion","hk"),
        ("áhrif",        "influence / effect","hk"),
        ("möguleiki",    "possibility",       "kk"),
        ("þroski",       "maturity / growth", "kk"),
        ("þröttur",      "weariness",         "kk"),
        ("rök",          "reason / argument", "hk"),
        ("tenging",      "connection",        "kvk"),
        ("þáttur",       "factor / episode",  "kk"),
        ("sköpun",       "creation",          "kvk"),
        ("þörmun",       "gratitude",         "kvk"),
        ("hugsjón",      "ideal / vision",    "kvk"),
        ("lyklar",       "keys",              "kk"),
        ("nákvæmni",     "precision",         "kvk"),
        ("þróun",        "development",       "kvk"),
        ("stigi",        "stage / level",     "kk"),
        ("spennufall",   "voltage drop",      "hk"),
        ("þjóðerni",     "nationality",       "hk"),
        ("þjóðlíf",      "national life",     "hk"),
        ("þjónusta",     "service",           "kvk"),
        # ── More family / people ──
        ("amma",         "grandmother",       "kvk"),
        ("afi",          "grandfather",       "kk"),
        ("tengdafaðir",  "father-in-law",     "kk"),
        ("tengdamóðir",  "mother-in-law",     "kvk"),
        ("mágur",        "brother-in-law",    "kk"),
        ("ráðgjafinn",   "the advisor",       "kk"),
        ("leiðsögumaður","guide",             "kk"),
        ("íþróttamaður", "athlete",           "kk"),
        ("söngkona",     "female singer",     "kvk"),
        ("söngari",      "singer",            "kk"),
        ("rithöfundur",  "author",            "kk"),
        ("leikari",      "actor",             "kk"),
        ("tónleikar",    "concert",           "kk"),
        ("listamaður",   "artist",            "kk"),
        ("dagskrá",      "programme / agenda","kvk"),
        ("flokkur",      "party / group",     "kk"),
        ("flokksmaður",  "party member",      "kk"),
        ("fulltrúi",     "representative",    "kk"),
        ("lögfræðingur", "lawyer",            "kk"),
        ("dómari",       "judge",             "kk"),
        ("dómstóll",     "court of law",      "kk"),
        ("lögreglumaður","police officer",    "kk"),
        ("lögreglustöð", "police station",    "kvk"),
        ("sjúkrahús",    "hospital",          "hk"),
        ("spítali",      "hospital",          "kk"),
        ("hjúkrunarfræðingur","nurse",        "kk"),
        ("læknir",       "doctor",            "kk"),
        ("þingmaður",    "MP",                "kk"),
        ("forseti",      "president / chairman","kk"),
        ("ráðherra",     "minister",          "kk"),
        ("dómsmálaráðherra","justice minister","kk"),
        # ── Environment / institution ──
        ("áskorun",      "challenge",         "kvk"),
        ("skrifstofa",   "office",            "kvk"),
        ("stofnun",      "institution",       "kvk"),
        ("þingsal",      "parliament chamber","kk"),
        ("borgarstjórn", "city council",      "kvk"),
        ("sveitarfélag", "municipality",      "hk"),
        ("kaupstaður",   "town",              "kk"),
        ("höfuðborg",    "capital city",      "kvk"),
        ("þjóðgarður",   "national park",     "kk"),
        ("safn",         "museum / collection","hk"),
        ("þjóðmenning",  "national culture",  "kvk"),
        ("þjóðsaga",     "folk tale",         "kvk"),
        ("þjóðlagslist", "folk art",          "kvk"),
        ("þjóðréttur",   "national right",    "kk"),
        ("þjóðlög",      "folk song",         "hk"),
        ("þjóðfundur",   "national assembly", "kk"),
        # ── Concepts ──
        ("hugmyndafræði","ideology",          "kvk"),
        ("heimspeki",    "philosophy",        "kvk"),
        ("trúarbrögð",   "religion",          "hk"),
        ("menntun",      "education",         "kvk"),
        ("námskeið",     "course",            "hk"),
        ("verkfræði",    "engineering",       "kvk"),
        ("stærðfræði",   "mathematics",       "kvk"),
        ("eðlisfræði",   "physics",           "kvk"),
        ("efnafræði",    "chemistry",         "kvk"),
        ("líffræði",     "biology",           "kvk"),
        ("sálfræði",     "psychology",        "kvk"),
        ("mannfræði",    "anthropology",      "kvk"),
        ("stjörnufræði", "astronomy",         "kvk"),
        ("jarðfræði",    "geology",           "kvk"),
        ("lyfjafræði",   "pharmacology",      "kvk"),
        ("hagfræði",     "economics",         "kvk"),
        ("bókmenntir",   "literature",        "kvk"),
        ("saga",         "history",           "kvk"),
        ("landafræði",   "geography",         "kvk"),
        ("málvísindi",   "linguistics",       "hk"),
        ("tölvunarfræði","computer science",  "kvk"),
        ("lögfræði",     "law",               "kvk"),
        # ── Common places ──
        ("verslun",      "shop / store",      "kvk"),
        ("apótek",       "pharmacy",          "hk"),
        ("krá",          "pub / tavern",      "kvk"),
        ("veitingastaður","restaurant",       "kk"),
        ("kaffihús",     "café",              "hk"),
        ("gisting",      "accommodation",     "kvk"),
        ("hótel",        "hotel",             "hk"),
        ("gistiheimili", "guesthouse",        "hk"),
        ("tjaldsvæði",   "campsite",          "hk"),
        ("sundlaug",     "swimming pool",     "kvk"),
        ("sundlaugin",   "the pool",          "kvk"),
        ("leikskóli",    "kindergarten",      "kk"),
        ("grunnskóli",   "primary school",    "kk"),
        ("háskóli",      "university",        "kk"),
        ("menntaskóli",  "grammar school",    "kk"),
        ("kirkja",       "church",            "kvk"),
        ("kirkjugarður", "churchyard",        "kk"),
        ("íbúðarhverfi", "residential area",  "hk"),
        ("iðnaðarsvæði", "industrial area",   "hk"),
        ("hlið",         "gate / side",       "kvk"),
    ],

    "Hlutir": [
        # ── More household objects ──
        ("sæti",         "seat",              "hk"),
        ("teppi",        "carpet / rug",      "hk"),
        ("töska",        "bag / briefcase",   "kvk"),
        ("mappa",        "folder / binder",   "kvk"),
        ("pósthólf",     "mailbox / PO box",  "hk"),
        ("púsl",         "puzzle",            "hk"),
        ("skúffa",       "drawer",            "kvk"),
        ("kista",        "chest / box",       "kvk"),
        ("geymir",       "tank / reservoir",  "kk"),
        ("kefli",        "rolling pin",       "hk"),
        ("sólhlíf",      "parasol / sunshade","kvk"),
        ("yfirborð",     "surface",           "hk"),
        ("þak",          "roof",              "hk"),
        ("lyftudyr",     "lift door",         "kvk"),
        ("dekk",         "tire / tyre",       "hk"),
        ("hjólbarði",    "tire / bicycle tire","kk"),
        ("leikfang",     "toy",               "hk"),
        ("dúkka",        "doll",              "kvk"),
        ("bikkja",       "toy dog",           "kvk"),
        ("spilakort",    "playing card",      "hk"),
        ("teningur",     "dice / cube",       "kk"),
        ("mynt",         "coin",              "kvk"),
        ("seðill",       "banknote",          "kk"),
        ("vegabréf",     "passport",          "hk"),
        ("nafnspjald",   "business card",     "hk"),
        ("kort",         "card / map",        "hk"),
        ("lykillinn",    "the key",           "kk"),
        ("lokar",        "locker",            "kk"),
        ("rúðu",         "windscreen",        "kvk"),
        ("þrautamál",    "riddle / problem",  "hk"),
        ("þvottavél",    "washing machine",   "kvk"),
        ("uppþvottavél", "dishwasher",        "kvk"),
        ("kælikassi",    "cool box",          "kk"),
        ("grill",        "grill / BBQ",       "hk"),
        ("gæla",         "favourite / dear",  "kvk"),
        ("hreinsiefni",  "cleaning product",  "hk"),
        ("þakavarningur","roof rack",         "kk"),
        ("kísill",       "silica / flint",    "kk"),
        ("slanga",       "hose / tube",       "kvk"),
        ("forðageymir",  "storage tank",      "kk"),
        ("tanki",        "tank",              "kk"),
        ("búferlabifreiðar","moving truck",   "kvk"),
        ("hjólagrind",   "bicycle frame",     "kvk"),
        ("beinagrind",   "skeleton",          "kvk"),
        ("hlutur",       "object / thing",    "kk"),
        ("venja",        "habit / custom",    "kvk"),
        ("mál",          "measure",           "hk"),
        ("hlutkæni",     "chance / lottery",  "kvk"),
        ("tól",          "tool",              "hk"),
        ("aðferð",       "method",            "kvk"),
        ("tjald",        "tent",              "hk"),
        ("svefnpoki",    "sleeping bag",      "kk"),
        ("lykillinn",    "the key (lykill)",  "kk"),
        ("þröstur",      "thrush (bird)",     "kk"),
        ("náttblær",     "night breeze",      "kk"),
        ("þungi",        "weight / heaviness","kk"),
        ("spón",         "chip / splinter",   "kvk"),
        ("tálkn",        "gills",             "hk"),
        ("hrekkur",      "trick / prank",     "kk"),
        ("skopstæling",  "parody",            "kvk"),
        ("gagn",         "benefit / use",     "hk"),
        ("merking",      "meaning / marking", "kvk"),
        ("bragð",        "taste / move",      "hk"),
        ("tónn",         "tone / sound",      "kk"),
        ("lag",          "tune / layer",      "hk"),
        ("hljómur",      "sound / harmony",   "kk"),
        ("díl",          "deal",              "kk"),
        ("kaffi",        "coffee",            "hk"),
        ("tafla",        "board / plate",     "kvk"),
        ("vörumerki",    "brand",             "hk"),
        ("etikett",      "label",             "hk"),
        ("prenta",       "print",             "kvk"),
        ("stimpill",     "stamp",             "kk"),
        ("litur",        "colour",            "kk"),
        ("hiti",         "heat / temperature","kk"),
        ("þrýstingur",   "pressure",          "kk"),
        ("styrkur",      "strength / force",  "kk"),
        ("orka",         "energy",            "kvk"),
        ("þróun",        "development",       "kvk"),
        ("breyting",     "change",            "kvk"),
        ("þvögun",       "pause",             "kvk"),
        ("tími",         "time / lesson",     "kk"),
        ("þáttur",       "episode / part",    "kk"),
        ("röð",          "row / order",       "kvk"),
        ("lína",         "line",              "kvk"),
        ("þversnið",     "cross-section",     "hk"),
        ("mál",          "size / case",       "hk"),
        ("mót",          "competition",       "hk"),
        ("stefna",       "direction / policy","kvk"),
        # ── More tools ──
        ("keyrsla",      "driving / run",     "kvk"),
        ("rekill",       "pusher / pestle",   "kk"),
        ("krull",        "curl / ring",       "kk"),
        ("flugur",       "fly (insect)",      "kvk"),
        ("leggur",       "tube / leg",        "kk"),
        ("takkinn",      "the button",        "kk"),
        ("lokar",        "stopper",           "kk"),
        ("þréðir",       "strands",           "kk"),
        ("kló",          "claw / hook",       "kvk"),
        ("niðurstaða",   "result",            "kvk"),
        ("skrá",         "list / file",       "kvk"),
        ("þarfir",       "needs",             "kvk"),
        ("þröstur",      "thrush",            "kk"),
        ("glas",         "glass (drink)",     "hk"),
        ("krús",         "mug",               "kvk"),
        ("bolli",        "cup",               "kk"),
        ("diskur",       "plate / disk",      "kk"),
        ("skál",         "bowl",              "kvk"),
        ("þvegill",      "washing cloth",     "kk"),
        ("þvottur",      "laundry",           "kk"),
    ],

    "Sagnir": [
        # Only active-voice, single-word verbs
        ("hella",        "to pour",           "so"),
        ("herða",        "to harden / tighten","so"),
        ("hrista",       "to shake",          "so"),
        ("hvíla",        "to rest",           "so"),
        ("hætta",        "to stop / quit",    "so"),
        ("kíkja",        "to peek",           "so"),
        ("kveðja",       "to say goodbye",    "so"),
        ("lúta",         "to bow / lean",     "so"),
        ("læsa",         "to lock",           "so"),
        ("prenta",       "to print",          "so"),
        ("stíga",        "to step",           "so"),
        ("svífa",        "to float / soar",   "so"),
        ("þenja",        "to stretch",        "so"),
        ("þykja",        "to seem / feel",    "so"),
        ("vinda",        "to wind / wrap",    "so"),
        ("flokka",       "to categorize",     "so"),
        ("lengja",       "to lengthen",       "so"),
        ("þrengja",      "to narrow",         "so"),
        ("víkja",        "to deviate",        "so"),
        ("springa",      "to burst",          "so"),
        ("smala",        "to gather sheep",   "so"),
        ("hlífa",        "to protect",        "so"),
        ("hnýta",        "to knot / tie",     "so"),
        ("sökkva",       "to sink",           "so"),
        ("lypa",         "to lip / whisper",  "so"),
        ("grafa",        "to dig",            "so"),
        ("glotta",       "to grin",           "so"),
        ("glaðast",      "to rejoice",        "so"),
        ("þagna",        "to fall silent",    "so"),
        ("gánga",        "to go",             "so"),
        ("fela",         "to conceal",        "so"),
        ("klappa",       "to clap",           "so"),
        ("þegja",        "to be silent",      "so"),
        ("vaða",         "to wade",           "so"),
        ("þjóna",        "to serve",          "so"),
        ("fletta",       "to flip / search",  "so"),
        ("þróast",       "to develop",        "so"),
        ("leiða",        "to lead",           "so"),
        ("glíma",        "to wrestle",        "so"),
        ("þagga",        "to hush",           "so"),
        ("geysa",        "to gush",           "so"),
        ("mæra",         "to praise",         "so"),
        ("draga",        "to pull / draw",    "so"),
        ("binda",        "to bind / tie",     "so"),
        ("þjappa",       "to pack tight",     "so"),
        ("þrífast",      "to thrive",         "so"),
        ("líkjast",      "to resemble",       "so"),
        ("gangast",      "to go / work out",  "so"),
        ("þykjast",      "to pretend",        "so"),
        ("leikast",      "to play",           "so"),
        ("nálgast",      "to approach",       "so"),
        ("þróast",       "to evolve",         "so"),
        ("þjást",        "to suffer",         "so"),
        ("takast",       "to succeed",        "so"),
        ("ganga",        "to work",           "so"),
        ("stíga",        "to step",           "so"),
        ("þrjóta",       "to run out",        "so"),
        ("skila",        "to deliver",        "so"),
        ("lenda",        "to land",           "so"),
        ("þurfa",        "to need",           "so"),
        ("geta",         "to be able",        "so"),
        ("mega",         "to be allowed",     "so"),
        ("munu",         "will / shall",      "so"),
        ("skulu",        "shall / must",      "so"),
        ("ljóstrast",    "to flash",          "so"),
        ("svíkja",       "to betray",         "so"),
        ("þykjast",      "to pretend",        "so"),
        ("ljóna",        "to shine",          "so"),
        ("deyfa",        "to numb",           "so"),
        ("mýkja",        "to soften",         "so"),
        ("harðna",       "to harden",         "so"),
        ("kólna",        "to cool down",      "so"),
        ("hitna",        "to warm up",        "so"),
        ("þorna",        "to dry out",        "so"),
        ("rakna",        "to get wet",        "so"),
        ("þorna",        "to wither",         "so"),
        ("lýðhenda",     "to rhyme",          "so"),
        ("svífa",        "to drift",          "so"),
        ("lyfta",        "to lift",           "so"),
        ("hreyfa",       "to move",           "so"),
        ("beygja",       "to bend / inflect", "so"),
        ("stíga",        "to climb",          "so"),
        ("hrekja",       "to chase away",     "so"),
        ("sýna",         "to show",           "so"),
        ("elta",         "to chase",          "so"),
        ("sækja",        "to seek",           "so"),
        ("þjóna",        "to wait on",        "so"),
        ("þagna",        "to quiet down",     "so"),
        ("liggja",       "to lie / be located","so"),
        ("fljóta",       "to float",          "so"),
        ("þjöppva",      "to compress",       "so"),
        ("minnka",       "to reduce",         "so"),
        ("stækka",       "to enlarge",        "so"),
        ("breikka",      "to widen",          "so"),
        ("flytja",       "to move house",     "so"),
        ("hýsa",         "to host / house",   "so"),
        ("rjúfa",        "to break / violate","so"),
        ("heilsa",       "to greet",          "so"),
    ],

    "Náttúra": [
        # More nature words (simple, single lemmas)
        ("gróður",       "vegetation",        "kk"),
        ("blóm",         "flower",            "hk"),
        ("lauf",         "leaf",              "hk"),
        ("þistill",      "thistle",           "kk"),
        ("lyng",         "heather",           "hk"),
        ("mosi",         "moss",              "kk"),
        ("sveppur",      "mushroom",          "kk"),
        ("fura",         "pine tree",         "kvk"),
        ("þara",         "seaweed",           "kk"),
        ("þörungur",     "algae",             "kk"),
        ("þangi",        "kelp",              "kk"),
        ("jarðvegur",    "soil",              "kk"),
        ("sandur",       "sand",              "kk"),
        ("leir",         "clay",              "kk"),
        ("mold",         "soil / earth",      "kvk"),
        ("grjót",        "rock / gravel",     "hk"),
        ("kalk",         "lime / calcium",    "hk"),
        ("kolefni",      "carbon",            "hk"),
        ("ísing",        "icing / freezing",  "kvk"),
        ("þruma",        "thunder",           "kvk"),
        ("elding",       "lightning",         "kvk"),
        ("brim",         "surf / breakers",   "hk"),
        ("alda",         "wave / swell",      "kvk"),
        ("bylgja",       "wave",              "kvk"),
        ("laug",         "hot spring",        "kvk"),
        ("lón",          "lagoon",            "hk"),
        ("kvos",         "cove / bay",        "kvk"),
        ("sund",         "sound / strait",    "hk"),
        ("hnjúkur",      "peak / summit",     "kk"),
        ("hlíð",         "hillside",          "kvk"),
        ("mýri",         "marsh / bog",       "kvk"),
        ("nes",          "headland / cape",   "hk"),
        ("gígur",        "crater",            "kk"),
        ("hraun",        "lava field",        "hk"),
        ("slétta",       "plain / flatland",  "kvk"),
        ("eyri",         "sandbar",           "kvk"),
        ("fjörður",      "fjord",             "kk"),
        ("regnbogi",     "rainbow",           "kk"),
        ("slydda",       "sleet",             "kvk"),
        ("brunni",       "well / spring",     "kk"),
        ("lækur",        "stream",            "kk"),
        ("þistilfjörður","thistle fjord",     "kk"),
        ("ísbreiða",     "ice sheet",         "kvk"),
        ("snjóflóð",     "avalanche",         "hk"),
        ("snjókarl",     "snowman",           "kk"),
        ("eldfjall",     "volcano",           "hk"),
        ("gufulindir",   "hot spring column", "kk"),
        ("víðir",        "willow",            "kk"),
        ("birki",        "birch",             "hk"),
        ("trjár",        "tree (pl.)",        "kk"),
        ("klöpp",        "flat rock",         "kvk"),
        ("hellur",       "stone slabs",       "kvk"),
        ("brjósk",       "cartilage",         "hk"),
        ("sjávarstrond", "coast / seashore",  "kvk"),
        ("strendur",     "coasts",            "kvk"),
        ("strand",       "beach / shore",     "kvk"),
        ("strönd",       "shore",             "kvk"),
        ("sjávardjúp",   "ocean depth",       "hk"),
        ("hafdjúp",      "ocean abyss",       "hk"),
        ("skógur",       "forest",            "kk"),
        ("hrísla",       "shrub / bush",      "kvk"),
        ("runni",        "shrub",             "kk"),
        ("kjarr",        "thicket",           "hk"),
        ("þúfa",         "tussock",           "kvk"),
        ("gras",         "grass",             "hk"),
        ("mó",           "moor",              "kk"),
        ("melur",        "sandy plain",       "kk"),
        ("hreysi",       "stone heap",        "hk"),
        ("vik",          "small bay / creek", "kvk"),
        ("vogur",        "bay / inlet",       "kk"),
        ("hólmur",       "islet / small island","kk"),
        ("skúti",        "cave / shelter",    "kk"),
        ("hellir",       "cave",              "kk"),
        ("gjá",          "rift / ravine",     "kvk"),
        ("þellingur",    "rock slab",         "kk"),
        ("klettur",      "cliff / crag",      "kk"),
        ("klappargrjót", "flat rocks",        "hk"),
        ("hnullungur",   "boulder",           "kk"),
        ("steinn",       "stone",             "kk"),
        ("sinni",        "opportunity / time","hk"),
        ("hiti",         "heat / temperature","kk"),
        ("kuldi",        "cold",              "kk"),
        ("rok",          "wind / gale",       "hk"),
        ("regn",         "rain",              "hk"),
        ("snjór",        "snow",              "kk"),
        ("ský",          "cloud",             "hk"),
        ("myrkur",       "darkness",          "hk"),
        ("birta",        "brightness",        "kvk"),
        ("dögg",         "dew",               "kvk"),
        ("þoka",         "fog / mist",        "kvk"),
        ("víðerni",      "vastness / expanse","hk"),
        ("umhverfi",     "environment",       "hk"),
        ("náttúra",      "nature",            "kvk"),
        ("landslag",     "landscape",         "hk"),
        ("hafsvæði",     "sea area",          "hk"),
        ("hlíðar",       "slopes",            "kvk"),
        ("fjöll",        "mountains",         "hk"),
    ],

    "Matur": [
        # More food vocabulary
        ("sulta",        "jam / preserve",    "kvk"),
        ("síróp",        "syrup",             "hk"),
        ("hunang",       "honey",             "hk"),
        ("sykur",        "sugar",             "kk"),
        ("salt",         "salt",              "hk"),
        ("pipar",        "pepper",            "kk"),
        ("edik",         "vinegar",           "hk"),
        ("olíuber",      "olive (berry)",     "hk"),
        ("möndla",       "almond",            "kvk"),
        ("hnetukjarna",  "walnut kernel",     "kk"),
        ("kasjú",        "cashew",            "hk"),
        ("pistasía",     "pistachio",         "kvk"),
        ("ávöxtur",      "fruit",             "kk"),
        ("kirsuber",     "cherry",            "hk"),
        ("bláber",       "blueberry",         "hk"),
        ("jarðarber",    "strawberry",        "hk"),
        ("bringebær",    "raspberry",         "hk"),
        ("gúldin",       "orange",            "kvk"),
        ("skrúfur",      "pasta screw shape", "kk"),
        ("pasta",        "pasta",             "hk"),
        ("pizza",        "pizza",             "kvk"),
        ("hamborgarinn", "the hamburger",     "kk"),
        ("hamborgar",    "hamburger",         "kk"),
        ("hotdog",       "hot dog",           "kk"),
        ("sandvís",      "sandwich",          "kk"),
        ("snakk",        "snack",             "hk"),
        ("namaskeið",    "snack course",      "hk"),
        ("eftirréttir",  "dessert",           "kk"),
        ("kaka",         "cake",              "kvk"),
        ("smákaka",      "cookie",            "kvk"),
        ("súkkulaðikaka","chocolate cake",    "kvk"),
        ("sítrónumarmelaði","lemon marmalade","hk"),
        ("ostakaka",     "cheesecake",        "kvk"),
        ("bláberjaskyr", "blueberry skyr",    "hk"),
        ("skyr",         "skyr (dairy)",      "hk"),
        ("búllan",       "the bun",           "kvk"),
        ("brauðmoli",    "breadcrumb",        "kk"),
        ("þurrkuð ávöxtur","dried fruit",     "kk"),
        ("lísúfur",      "liqueur",           "kk"),
        ("bjór",         "beer",              "kk"),
        ("vín",          "wine",              "hk"),
        ("kaffi",        "coffee",            "hk"),
        ("te",           "tea",               "hk"),
        ("vatn",         "water",             "hk"),
        ("safi",         "juice",             "kk"),
        ("mjólk",        "milk",              "kvk"),
        ("rjómi",        "cream",             "kk"),
        ("smjör",        "butter",            "hk"),
        ("ostur",        "cheese",            "kk"),
        ("skyr",         "skyr",              "hk"),
        ("hafragrautur", "oatmeal / porridge","kk"),
        ("kornflögur",   "cornflakes",        "kvk"),
        ("súkkulaðibollur","chocolate bun",   "kk"),
        ("kleinur",      "twisted doughnut",  "kvk"),
        ("laufabrauð",   "leaf bread",        "hk"),
        ("hangikjöt",    "smoked lamb",       "hk"),
        ("harðfiskur",   "dried fish",        "kk"),
        ("sólskínssíld", "sunshine herring",  "kvk"),
        ("plokkfiskur",  "fish stew",         "kk"),
        ("kjötsúpa",     "lamb soup",         "kvk"),
        ("grænmetissúpa","vegetable soup",    "kvk"),
        ("pyls",         "frankfurter",       "kk"),
        ("pylsa",        "sausage",           "kvk"),
        ("beikon",       "bacon",             "hk"),
        ("skinka",       "ham",               "kvk"),
        ("kjötbollur",   "meatballs",         "kvk"),
        ("steik",        "steak",             "kvk"),
        ("lambakjöt",    "lamb meat",         "hk"),
        ("nautakjöt",    "beef",              "hk"),
        ("svínakjöt",    "pork",              "hk"),
        ("kjúklingur",   "chicken",           "kk"),
        ("egg",          "egg",               "hk"),
        ("smjöregg",     "fried egg",         "hk"),
        ("hörpudiskur",  "scallop",           "kk"),
        ("smokkfiskur",  "squid",             "kk"),
        ("tindabikkja",  "dogfish",           "kvk"),
        ("lúða",         "halibut",           "kvk"),
        ("skarkoli",     "plaice",            "kk"),
        ("ýsa",          "haddock",           "kvk"),
        ("steinbítur",   "wolffish",          "kk"),
        ("bleikja",      "arctic char",       "kvk"),
        ("silungur",     "trout (fresh)",     "kk"),
        ("niðursoðin mat","canned food",      "kk"),
        ("niðursoðinn",  "canned",            "kk"),
        ("hrísgrjón",    "rice",              "hk"),
        ("quinoa",       "quinoa",            "kvk"),
        ("linsubaunir",  "lentils",           "kvk"),
        ("fitufrí",      "fat-free",          "hk"),
        ("vítamín",      "vitamin",           "hk"),
        ("prótín",       "protein",           "hk"),
        ("kolvetni",     "carbohydrate",      "hk"),
        ("fita",         "fat",               "kvk"),
        ("kaloría",      "calorie",           "kvk"),
    ],

    "Líkami": [
        # More body parts and medical terms
        ("bringa",       "chest / sternum",   "kvk"),
        ("rifbein",      "rib",               "hk"),
        ("kviður",       "abdomen",           "kk"),
        ("nöf",          "belly button",      "kvk"),
        ("kynfæri",      "genitals",          "hk"),
        ("rassinn",      "buttock",           "kk"),
        ("takmark",      "temple (head)",     "hk"),
        ("kinn",         "cheek",             "kvk"),
        ("kjálki",       "jaw",               "kk"),
        ("góm",          "palate / gum",      "kk"),
        ("þröngull",     "thyroid",           "kk"),
        ("lungu",        "lung (inflected)",  "hk"),
        ("slagæð",       "artery",            "kvk"),
        ("þarmur",       "intestine",         "kk"),
        ("mein",         "disease / ailment", "hk"),
        ("bólga",        "inflammation",      "kvk"),
        ("sár",          "wound",             "hk"),
        ("brenna",       "burn",              "kvk"),
        ("þunglyndi",    "depression",        "hk"),
        ("kvíði",        "anxiety",           "kk"),
        ("sykursýki",    "diabetes",          "kvk"),
        ("blóðþrýstingur","blood pressure",   "kk"),
        ("skurðaðgerð",  "surgery",           "kvk"),
        ("blóðrannsókn", "blood test",        "kvk"),
        ("lyfjagjöf",    "drug administration","kvk"),
        ("meðferð",      "treatment",         "kvk"),
        ("greining",     "diagnosis",         "kvk"),
        ("lyf",          "medicine",          "hk"),
        ("tafla",        "tablet (medicine)", "kvk"),
        ("sprautur",     "injection",         "kvk"),
        ("sýking",       "infection",         "kvk"),
        ("ofnæmi",       "allergy",           "hk"),
        ("veikindi",     "illness",           "hk"),
        ("sjúkdómur",    "disease",           "kk"),
        ("krabbamein",   "cancer",            "hk"),
        ("hjartasjúkdómur","heart disease",   "kk"),
        ("blóðlækkun",   "anemia",            "kvk"),
        ("meinlæti",     "suffering",         "hk"),
        ("eymslar",      "soreness",          "kvk"),
        ("þroti",        "swelling",          "kk"),
        ("brot",         "fracture",          "hk"),
        ("slæðingur",    "sprain / bruise",   "kk"),
        ("krampi",       "cramp",             "kk"),
        ("magi",         "stomach",           "kk"),
        ("brisi",        "pancreas",          "kk"),
        ("milti",        "spleen",            "hk"),
        ("æðaríkur",     "vascular",          "kk"),
        ("taugakerfi",   "nervous system",    "hk"),
        ("beinagrindin",  "the skeleton",     "kvk"),
        ("hörund",       "flesh / skin",      "hk"),
        ("fita",         "fat (body)",        "kvk"),
        ("vöðvamassi",   "muscle mass",       "kk"),
    ],

    "Klæði": [
        # More clothing and accessories
        ("regnkápa",     "raincoat",          "kvk"),
        ("sloppur",      "dressing gown",     "kk"),
        ("sokkar",       "socks",             "kk"),
        ("höndlaband",   "wristband",         "hk"),
        ("höfuðbúnaður", "headgear",          "kk"),
        ("skóband",      "shoelace",          "hk"),
        ("klæðnaður",    "garments",          "kk"),
        ("ull",          "wool",              "kvk"),
        ("bómull",       "cotton",            "kvk"),
        ("nylon",        "nylon",             "hk"),
        ("flís",         "fleece",            "kvk"),
        ("skinn",        "skin / hide",       "hk"),
        ("búningur",     "costume",           "kk"),
        ("skikkja",      "cloak / cape",      "kvk"),
        ("íþróttajakki", "sports jacket",     "kk"),
        ("sundbolur",    "swimsuit top",      "kk"),
        ("sundur",       "swim / swimming",   "hk"),
        ("öryggisvesti", "safety vest",       "hk"),
        ("vinnuhandskur","work glove",        "kk"),
        ("höfuðklæði",   "headscarf",         "hk"),
        ("línskyrta",    "linen shirt",       "kvk"),
        ("silkibleikja", "silk blouse",       "kvk"),
        ("lúxuspeysa",   "luxury jumper",     "kvk"),
        ("löðrungur",    "leather jacket",    "kk"),
        ("ullarpeysa",   "wool sweater",      "kvk"),
        ("tvíröð",       "double-breasted",   "kvk"),
        ("bókfinnur",    "book strap",        "kk"),
        ("hárspenna",    "hair clip",         "kvk"),
        ("hárlúfa",      "scrunchie",         "kvk"),
        ("eyrnamói",     "earring",           "kk"),
        ("hringur",      "ring",              "kk"),
        ("armband",      "bracelet",          "hk"),
        ("gullhringur",  "gold ring",         "kk"),
        ("silfurhringur","silver ring",       "kk"),
        ("brjóstspenna", "brooch",            "kvk"),
        ("bandalag",     "alliance",          "hk"),
        ("þráður",       "thread",            "kk"),
        ("nál",          "needle",            "kvk"),
        ("siðferðileg",  "ethical",           "kvk"),
        ("hannaður",     "designed",          "kk"),
        ("verðgildi",    "value / worth",     "hk"),
        ("verðlag",      "price level",       "hk"),
    ],

    "Dýr": [
        # More animals with simpler lemmas
        ("stari",        "starling",          "kk"),
        ("þúfutittlingur","meadow pipit",     "kk"),
        ("snjótittlingur","snow bunting",     "kk"),
        ("tjaldur",      "oystercatcher",     "kk"),
        ("lóa",          "golden plover",     "kvk"),
        ("þvari",        "dunlin",            "kk"),
        ("músarindill",  "wren",              "kk"),
        ("grákráka",     "hooded crow",       "kvk"),
        ("hrafn",        "raven",             "kk"),
        ("rauðbrystingur","robin",            "kk"),
        ("máfur",        "gull",              "kk"),
        ("svartfugl",    "black guillemot",   "kk"),
        ("stuttnefja",   "razorbill",         "kvk"),
        ("þursaskarfur", "great skua",        "kk"),
        ("reiðingur",    "red kite",          "kk"),
        ("heiðagæs",     "pink-footed goose", "kvk"),
        ("grágæs",       "greylag goose",     "kvk"),
        ("grasönd",      "mallard",           "kvk"),
        ("urriði",       "brown trout",       "kk"),
        ("lúða",         "halibut",           "kvk"),
        ("ýsa",          "haddock",           "kvk"),
        ("skarkoli",     "plaice",            "kk"),
        ("bleikja",      "arctic char",       "kvk"),
        ("silungur",     "trout",             "kk"),
        ("ufsi",         "saithe",            "kk"),
        ("hlýri",        "pollock",           "kk"),
        ("steinbítur",   "wolffish",          "kk"),
        ("lúður",        "plaice (var.)",     "kk"),
        ("skrúður",      "wrasse",            "kk"),
        ("krókatindur",  "angler fish",       "kk"),
        ("þorskur",      "cod",               "kk"),
        ("síld",         "herring",           "kvk"),
        ("smokkfiskur",  "squid",             "kk"),
        ("hörpudiskur",  "scallop",           "kk"),
        ("krabbadýr",    "crustacean",        "hk"),
        ("skeldýr",      "shellfish",         "hk"),
        ("lindýr",       "mollusc",           "hk"),
        ("blöðrumaður",  "jellyfish",         "kk"),
        ("þang",         "seaweed",           "hk"),
        ("marfluga",     "sandhopper",        "kvk"),
        ("spönglur",     "fluke / flounder",  "kvk"),
    ],

    "Nýyrði": [
        # More tech / modern concepts (noun lemmas that pass BÍN)
        ("vefur",        "web",               "kk"),
        ("þjónn",        "server",            "kk"),
        ("biðröð",       "queue",             "kvk"),
        ("grein",        "branch (code)",     "kvk"),
        ("smárit",       "blog",              "hk"),
        ("netverslun",   "online shop",       "kvk"),
        ("lykillinn",    "the key (password)","kk"),
        ("tæknilæsi",    "tech literacy",     "hk"),
        ("gagnagrunnur", "database",          "kk"),
        ("skjávarpi",    "projector",         "kk"),
        ("fjórhæðir",    "four storeys",      "kvk"),
        ("tækni",        "technology",        "kvk"),
        ("þjálfun",      "training (AI)",     "kvk"),
        ("hlutgreining", "object detection",  "kvk"),
        ("myndgreining", "image analysis",    "kvk"),
        ("gagnavinnsla", "data processing",   "kvk"),
        ("reiknilíkan",  "calculation model", "hk"),
        ("líkindamál",   "probability",       "hk"),
        ("þverþekking",  "cross-knowledge",   "kvk"),
        ("forritun",     "programming",       "kvk"),
        ("forritari",    "programmer",        "kk"),
        ("kerfisþróun",  "system development","kvk"),
        ("þróunarteymi", "development team",  "hk"),
        ("snertiborð",   "touchpad",          "hk"),
        ("snertiskjár",  "touchscreen",       "kk"),
        ("gæðaprófun",   "quality testing",   "kvk"),
        ("sjálfvirkni",  "automation",        "kvk"),
        ("þjónustuver",  "service centre",    "hk"),
        ("notendaviðmót","user interface",    "hk"),
        ("þörfin",       "the need",          "kvk"),
        ("uppfærsla",    "update",            "kvk"),
        ("villuleit",    "debugging",         "kvk"),
        ("hlutur",       "object (OOP)",      "kk"),
        ("klassi",       "class (OOP)",       "kk"),
        ("aðferð",       "method (OOP)",      "kvk"),
        ("fallaklösi",   "exception class",   "kk"),
        ("forritsgrein", "code branch",       "kvk"),
        ("samhliða",     "parallel",          "kvk"),
        ("samloðun",     "cohesion",          "kvk"),
        ("þjóðflokkun",  "national taxonomy", "kvk"),
        ("biðminni",     "buffer memory",     "hk"),
        ("flæðirit",     "flowchart",         "hk"),
    ],
}
